### PR TITLE
Update lookup libraries to return CodeableConcept object

### PR DESCRIPTION
**Pull request by danlee1025**
Update lookup libraries to return CodeableConcept objects.

- Updated lists with codeSystem and code properties so that they are uniform across the different lookup libraries.
- Added tests for the new getCodeableConcept functions.
- Added utility library to get CodeableConcept tuple from list.
- Renamed lookup libaries to match object model name.

   - Let me know if I should change the names.  I changed toxicity_lookup -> toxicreactiontotreatment_lookup.  It looks ugly but we wanted it all lowercase and to match the object model classname.  Do we want this camelCased?  
   -  stage_lookup -> tnmstage_lookup

These libraries will hopefully facilitate hiding the coding within the objects when we modify the getters/setters in the object model(We plan to automate this process...).  This can be merged into master as the new functions are not currently being used.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] N/A Cheat sheet is updated
- [x] N/A Demo script is updated 
- [x] N/A Documentation on Wiki has been updated 
- [x] N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] N/A Added UI tests for slim mode 
- [x] N/A Added UI tests for full mode
- [x] Added backend tests for fluxNotes code
- [x] N/A Added note parser examples to test new functionality

## Reviewer 1: Greg

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
This looks good. I think it's going to make things a lot easier to deal with!
[GQ1] Can you make getStatusCodeableConcept and getReasonCodeableConcept in progression_lookup use the status.codeSystem instead of hard-coding the code system? I know they are all the same, but just in case that changes in the future.

**Comment by gregquinn2001** [comment]
[GQ2] I'm torn on codeable_concept.jsx. I'm thinking the code in there should live in the CodeableConcept class within the model as a static function? At the very least, the utility function should live in a class like CodeableConceptUtils as a static function and be in the model directory. This is object model stuff so I feel like it should live somewhere in there. Thoughts?

**Comment by gregquinn2001** [comment]
[GQ3] In toxicity_lookup, can you update getAttributionCodeableConcept to use code for the value (instead of # plus name) and codesystem for the codesystem instead of hard coding it.

**Comment by gregquinn2001** [comment]
[GQ4] getGradeCodeableConcept in toxicity_lookup has the same issue. It should use grade.codeSystem for the codesystem instead of hard coding it.

**Comment by gregquinn2001** [comment]
[GQ5] getAdverseEventCodeableConcept also hard codes codesystem.

**Comment by danlee1025** [comment]
Hi Greg, are you looking at the hide-coding-in-objects branch?  There used to be an update-lookup-libraries branch that has been deleted(you may have a local copy.).  I believe GQ1, GQ3, and GQ4 are addressed there.

For GQ2, I can rename and move it to the model directory.  Should I create a lib or utils directory inside of model.

For GQ5, I began adding code and codeSystem into the adverseEventsOptions list but realized it would take a good amount of time to accomplish(This list spans more than 8000 lines).  Do you want me to add those 2 properties to that list?

**Comment by gregquinn2001** [comment]
I was looking at the code using github PR web UI. strange. Fine on GQ5. don't worry about it

**Comment by gregquinn2001** [comment]
For GQ2, not sure what's best yet. I guess just put it directly in model folder

**Comment by danlee1025** [comment]
Hmm interesting, are the files updated now or do you still see the previous problems?

**Comment by gregquinn2001** [comment]
not in the pr display of files changed for me

**Comment by gregquinn2001** [comment]
wait maybe. I'm confused now. It does look different

**Comment by gregquinn2001** [comment]
ok. don't worry about those 3 then

**Comment by danlee1025** [comment]
I addressed GQ2 and rebased off of updates to master.

**Comment by nicoleng12** [comment]
This looks good Dan! Your back end tests are thorough. Nice job!

**Pull request merged**
