### PR TITLE
Date picker component

### PR DESCRIPTION
**Pull request by nicoleng12**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Created a Date Picker component for slim mode so that it is easier for developers to implement date picker within the app. Updated disease status, clinical trial, and deceased forms to use the new component for selecting dates. Update UI tests testing the date picker

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] N/A Cheat sheet is updated
- [x] N/A Demo script is updated 
- [x] N/A Documentation on Wiki has been updated 
- [x] N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] N/A Added UI tests for slim mode 
- [x] N/A Added UI tests for full mode
- [x] N/A Added backend tests for fluxNotes code
- [x] N/A Added note parser examples to test new functionality

## Reviewer 1: Julia

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Mike T

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

### CODE REVIEW

**Comment by danlee1025** [comment]
In ProgressionForm.jsx, the id passed to the DatePicker is 'date-of-death', but it should probably be something else.  Otherwise, everything looks great!

**Comment by nicoleng12** [comment]
Nice catch @danlee1025 ! I fixed it

**Comment by nicoleng12** [comment]
Rebased on master after Julia's branch got merged

**Comment by mtorchio** [comment]
This branch looks great Nicole! The date picker is straightforward and has a clean design. I'm running the tests now.

**Comment by mtorchio** [comment]
Since this has been rebased, I think we're ready to merge it. I can do the merge.

**Pull request merged**
