### PR TITLE
Add google analytics

### PR DESCRIPTION
**Pull request by Dtphelan1**
Pretty self explanatory. To verify it works, you have to be logged into Google Analytics. I'm not quite sure what we want to do about that in terms of credential sharing. I was originally emailed the details, but that seems like a bad medium by which to share these details. Maybe store them in our share folder? Do people have thoughts?

### CODE REVIEW

**Comment by nicoleng12** [comment]
Are you using your MITRE credentials for Google Analytics? Can there be multiple users tracking a site's traffic?

**Comment by Dtphelan1** [comment]
I'm using SHR-team-wide google analytics credentials. These are credentials that shouldn't be linked back to any person in particular, but the account does monitor the analytics of the SHR website, the Synthea website and now FluxNotes

**Comment by mtorchio** [comment]
I think the proper way to share passwords is an encrypted email to individuals (not the team mailing list). I can't really review this without the username and password.

There's a separate question of how to manage and distribute the reports from Google Analytics, Andre seems to prefer sending those by email as well.

**Comment by gregquinn2001** [comment]
I added Andre as a reviewer to this one. I think he needs to be the final vote on whether this is what he was looking for.

**Comment by nicoleng12** [comment]
This looks good. I got the credentials from Dylan and tested it. Considering that this task was just to set up google analytics, I think it's accomplished that. We can make another jira for how we want to share the data but as Greg pointed out, let's wait for @andrequina to do the final review.

**Comment by Dtphelan1** [comment]
Sure! I think that so long as we have basic analytics set up, we can start developing more complex tasks for specific actions we want tracked, but either way having Andre take a look is a good idea. I'll try to flag him down sometime today!

**Comment by Dtphelan1** [comment]
@gregquinn2001 Just talked with Andre and what we've done meets his requirements for the task. What he's looking to start tracking is high-level information about visits to the website, which we currently collect with what we're tracking. As we start piloting we can look into more granular user-behavior tracking, but this is exactly what we need to start answering the kinds of questions he wanted to address (i.e. who's using the site, where are they located, what areas are visiting the site most frequently, etc...)

**Comment by Dtphelan1** [comment]
Rebased and merging!

**Comment by Dtphelan1** [comment]
Rebased and merging!

**Pull request merged**
