### PR TITLE
Update SummaryMetadata to specify type in each section

### PR DESCRIPTION
**Pull request by danlee1025**
- Added type field to each section object in SummaryMetadata.
- Renamed collection field to data in SummaryMetadata.
- Moved 2 column logic from DataSummaryPanel to DataSummaryTable so that each section is divided individually instead of dividing up all sections into 2 columns.
- Added logic in DataSummaryPanel to look at the type of the section to decide what component to render.
     -  Currently only supports type of 'NameValuePairs'.
     -  In the future, we might create a component manager to allow the user to choose different views based on the data type in each section.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- Cheat sheet is updated
- Demo script is updated 
- Documentation on Wiki has been updated 
- Additional technical components and libraries are documented and added to wiki as needed

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- Added UI tests for slim mode 
- Added UI tests for full mode
- Added backend tests for fluxNotes code
- Added note parser examples to test new functionality

## Reviewer 1: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
This looks good Dan. All tests pass. Nice job moving the division of columns into the specific section.

**Comment by jafeltra** [comment]
This looks good to me! All the tests pass and adding a data type of NameValuePairs seems like a good approach to me!

The one question that I have is about splitting the tables into two columns at the individual section level. I talked to Nicole about this so I understand the benefits of doing it this way so that the full section stays together and you have more control over each section individually. But it seems like now we have a lot more unused space on the right side of the screen since the majority of our tables only have one subsection. The designs for this might still be changing so I don't think this is an immediate problem, but I figured I'd mention it.

**Comment by gregquinn2001** [comment]
@jafeltra . good question. I think we should monitor it but my assumption is the amount of data will only increase...

**Comment by danlee1025** [comment]
Just rebased the branch...

@jafeltra Yeah I agree it doesn't look as great with the amount of data we have now.  I mentioned to Greg this morning that it looked "ugly".

We would have faced problems in the future when we added sections that wanted to span the whole screen on its own(e.g. Timeline).  With how it was previously, it would have shrunk it into one column.

**Comment by jafeltra** [comment]
@daniellee1025 and @gregquinn2001 thanks for the answers! I think what you both said makes sense. It definitely seems much more useable and flexible this way, and you're right we will probably get more data. So as long as we keep an eye out for it and are aware if it, I'm good with keeping it this way for now.

**Pull request merged**
