### PR TITLE
Partial solution to inline helper 

### PR DESCRIPTION
**Pull request by Dtphelan1**
Detects a shorthand keyword (.stage) followed by a space. Adds in-line helper text and allows users to edit the newly introduced areas.

### CODE REVIEW

**Comment by gregquinn2001** [comment]
can we change .stage to .staging since it seems like staging would be TNM and stage would be roman numeral followed by letter like IIA

**Comment by Dtphelan1** [comment]
Changed terminology @gregquinn2001

**Comment by gregquinn2001** [comment]
lets get rid of work "information" in expansion as well

**Comment by gregquinn2001** [comment]
so we don't have the ability to type in the fields yet? That was part of this task. Do we think we can do it with slate?

**Comment by Dtphelan1** [comment]
Current solution fails to address the continued typing behavior; this code will still be merged in to allow for parallel development on a slate.js drive editor section as opposed to master's current draft.js editor.

**Pull request merged**
