### PR TITLE
Integrating staging library functions

### PR DESCRIPTION
**Pull request by cjduffett**
Added the new staging library for computing prognostic stage. Changed the tumorSize, nodeSize, and metastasis variables to be strings representing the T,N,M values.

### CODE REVIEW

**Comment by Dtphelan1** [comment]
It seems like we've re-coupled the staging values (T,N,M) with the Stage value, something we'll have to undo when we begin moving towards new in-line helpers like' .stage'. Since that won't be necessary for the demo, I'm fine merging this as is.

**Comment by Dtphelan1** [comment]
Looks like the staging library makes an assumption wherein if the M value isn't M1, it's assumed to be M0. This results in staging information before the M value has been entered and is incorrect. Once this is addressed it looks ready to merge.

**Comment by cjduffett** [comment]
Fixed with https://github.com/standardhealth/flux/pull/28

**Comment by Dtphelan1** [comment]
So it looks like a few value combinations are undefined. Is this expected behavior as far as the manuals are concerned? If so, it looks clean to merge

**Comment by Dtphelan1** [comment]
Was able to confirm that some of these combinations are undefined in the AJCC manual. I'm good to merge.

**Pull request merged**
