### PR TITLE
Enrollment and unenrolled structured phrases

### PR DESCRIPTION
**Pull request by nicoleng12**
This PR addresses jira issues 936 and 937. 

Broke up clinical trials structured phrase into 2: one for enrollment of a patient in a trial and one for when the patient has unenrolled from a trial. The word "enrollment" was chosen based on Joey's notes. The world "unenrolled" was chosen after speaking with @gregquinn2001 and deciding that for speaking purposes it seemed natural to say "a patient unenrolled from a trial". 

This PR includes:
- addition of #enrollment structured phrase to add info for when a patient has enrolled in a trial (ex. "...informed consent was obtained for #enrollment #PATINA #02/14/2018")
- addition of #unenrolled structured phrase to add info for when a patient unenrolls from a trial (ex. "...patient #unenrolled #PATINA #02/15/2018"
- removed #on from enrollment and unenrolled. Just need to use #date now (don't need this extra layer of child shortcuts since no longer using #clinical trial which includes enrollment and end date)
- Updated forms in slim mode so that #enrollment and #unerolled each have their own page 
- Updated cheat sheets to remove #clinical trials and instead have #enrollment and #unenrolled
-  Fixed broken tests
- Added backend and front end tests (full and slim mode)
- Updated note parser sample notes

Known issues:
- Made 2 jira issues to cover a couple of bugs that were encountered: https://jira.mitre.org/browse/ASCODCP-943 and https://jira.mitre.org/browse/ASCODCP-955 

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] Added UI tests for slim mode 
- [x] Added UI tests for full mode
- [x] Added backend tests for fluxNotes code
- [x] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Awesome and thorough pull request!
[GQ1] Can we throw a few additional words into the structured phrases generated by slim mode to make them flow better? For example, #enrollment in #PATINA on #01/30/2018

**Comment by nicoleng12** [comment]
Thanks for the review! GQ1 has been addressed.

**Comment by nicoleng12** [comment]
@jafeltra pointed out that I had commented out the slim mode tests. I fix that so that slim mode tests are uncommented now

**Comment by jafeltra** [comment]
This looks good to me! The new shortcuts work in full mode, the new phrases in slim mode work, all the existing and new tests pass, and the note parser correctly parses the sample notes.

**Pull request merged**
