### PR TITLE
Used date picker lib in slim mode

### PR DESCRIPTION
**Pull request by nicoleng12**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

Originally, slim mode was using an html date picker for selecting dates in slim mode (specifically for reference date in disease status form, enrollment date and end date for clinical enrollment form, and date of death on the deceased form). The date picker component does not render in IE. To fix this, replaced the html date picker component with the react-day-picker component (https://github.com/gpbl/react-day-picker) 

## Submitter:

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] N/A Cheat sheet is updated
- [x] N/A Demo script is updated 
- [x] Documentation on Wiki has been updated 
- [x] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] N/A Added UI tests for slim mode 
- [x] N/A Added UI tests for full mode
- [x] N/A Added backend tests for fluxNotes code
- [x] N/A Added note parser examples to test new functionality

## Reviewer 1: Dan Lee

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Laura

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

### CODE REVIEW

**Comment by laclark22** [comment]
LC1- When you select a Enrollment Date in IE it populates the End Date with that date as well and vice versa.

**Comment by gregquinn2001** [comment]
We should add testing on Chrome and IE to the definition of done although that's difficult for Julia so she may be exempt and her reviewers need to make sure to try it on IE on Windows.

**Comment by nicoleng12** [comment]
@laclark22 Yikes! Nice catch. I know what I did wrong so I can fix that right away. It's also happening in Chrome too. @gregquinn2001 That is a good suggestion. We do have IE and Chrome in our automated tests but we can definitely add that to our manual tests as well.

**Comment by nicoleng12** [comment]
@laclark22 [LC1] has been fixed

**Comment by nicoleng12** [comment]
@gregquinn2001 Updated the template for pull requests to include manual testing in IE and in chrome so future pull requests will have that check. I also updated the Developer Definition of Done in the project wiki to include manual testing in IE and Chrome

**Comment by gregquinn2001** [comment]
thanks @nicoleng12  and thanks to everyone for reviewing so quickly!

**Pull request merged**
