### PR TITLE
Implement add note button

### PR DESCRIPTION
**Pull request by nicoleng12**
This PR addresses jira issues 803 and 773. It also seems to fix the bug reported in the backlog (https://jira.mitre.org/browse/ASCODCP-709). Can others help verify this? 

Jira issue 803:
- Clicking new note button in post-encounter mode clears the editor content and adds a new note in patient record, which is added to and is displayed in the list of clinical notes
- Clicking new note button in pre-encounter mode changes the layout to add the note editor
- Once the editor is added to the layout, clicking new note button clears the content in pre encounter mode
- Added UI tests to check that content is cleared in post and pre encounter modes as well as check that the editor is added in pre encounter mode when the new note button is pressed
- Implementing add new note button functionality seems to have fixed jira issue 709

Jira issue 773:
(This branch has been merged with @jafeltra 's branch which addresses issue 773)
- @jafeltra added signed/unsigned field to clinical notes
- @jafeltra added functionality to display in progress notes in clinical notes viewer. Unsigned notes are displayed as in progress notes whereas signed notes appear in the main list
- @jafeltra added initial functionality to visualize a selected note with a blue boarder. 773 did not actually include being able to view the content of a note in the editor.
- @jafeltra added a UI test to verify that in progress note are added to the clinical notes view as new notes are added (new note button is pressed)

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- [x] Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] I think it would make more sense to put isNoteViewerVisible and isNoteViewerEditable in the state of Note Assistant. I don't think any components outside of that know about/use those state values, right? FullApp shouldn't know anything about those state values specific to blackbox components it uses. Tell me if there is some reason others need that state though...

**Comment by nicoleng12** [comment]
For GQ1, isNoteViewerVisible and isNoteViewerEditable are in ClinicalDashboard (parent of NotesPanel and NoteAssistant) because the layout of the dashboard depends on whether or not these values are true or false. For example, for pre encounter mode, the default view is to just have the targeted data panel and note assistant, not the note viewer. This drives the layout that it will have. I'm definitely open to other ways of doing this but this is what we have been using at the moment to determine the layouts.

**Comment by gregquinn2001** [comment]
Ok ClinicalDashboard would be fine, but I see them being initialized in FullApp according to the diffs in github. Am I reading it wrong?

**Comment by nicoleng12** [comment]
Nope you are right. It's initialized in FullApp. FullApp can have different dashboards with different layouts. ClinicalDashboard is one of multiple layouts that we can have. There's also a placeholder for a "PatientDashboard" which we're not using at the moment. I think for now we should keep it in FullApp, otherwise each dashboard will have to define their own flags for isvisible, iseditable, as well as the layout (another variable used for setting sizing of layouts )

**Comment by gregquinn2001** [comment]
My point is that a FullApp only know about dashboards - not notes editors. Not all dashboards will allow clinical note editing/viewing potentially. A patient-facing portal for example may use a different view of the data. I think we should keep state at the lowest level we can to match where it's used. Besides, if one dashboard has the note viewer showing and then you switch dashboards, should it necessarily mean the note viewer is still showing or might it be hidden in that dashboard initially? We'd want 2 different state variables for the dashboards as we don't necessarily know if we want them impacting each other.

**Comment by gregquinn2001** [comment]
We can talk by skype if I'm confusing things!

**Comment by gregquinn2001** [comment]
@nicoleng12  and I just spoke via skype. We agreed that ideally state would be maintained at the lowest level it can, but with redux around the corner changing our model for state in the app, we opted to not worry about this any further. Ignore GQ1.

**Comment by nicoleng12** [comment]
Rebased on master

**Pull request merged**
