### PR TITLE
Resize components correctly

### PR DESCRIPTION
**Pull request by jafeltra**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

This makes it so that the LineChart and Timeline Visualizers get resized properly when switching Views (pre/post encounter). The timeline component handled resizing differently than the line chart, so the solutions for fixing each were slightly different.

The Jira item for this task also mentioned considering whether to change the display for tabular components that only have one table. After talking with Greg, I'm going to make a separate Jira to handle that.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [] Cheat sheet is updated
- [] Demo script is updated 
- [] Documentation on Wiki has been updated 
- [] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [] Added UI tests for slim mode 
- [] Added UI tests for full mode
- [] Added backend tests for fluxNotes code
- [] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
It doesn't look like this addresses the Minimap, which was also a part of this task, but the minimap issue isn't as poignant as the other issues were so I'm find with this. @gregquinn2001 do you have any thoughts?  Also great find re: the timeline resizer!

**Comment by jafeltra** [comment]
I just rebased the branch and fixed a few issues that came up with the rebase. The timeout for componentDidMount was incorrect, making the new Progression chart that gets added in Pre-Encounter not resize correctly.

@Dtphelan1  I'm not completely sure what needs to get resized on the Minimap. Can you explain where it isn't resizing correctly?

**Comment by jafeltra** [comment]
Dylan and I talked and I can see what he is referring to on master, but I can't recreate it on this branch. I'm not sure if some of the other resizing inadvertently fixed the minimap resizing issues. For now, I'm not sure how to fix anything since I don't see any minimap resizing issues anymore. If anyone else does still see it, let me know!

**Comment by nicoleng12** [comment]
Strange... I do see what you are talking about @Dtphelan1 on master, but I do not see this same behavior on @jafeltra 's branch here. I am testing on chrome and IE at 100% zoom

**Comment by gregquinn2001** [comment]
@Dtphelan1 can you reproduce on Julia's branch?

**Comment by nicoleng12** [comment]
After talking with @gregquinn2001 , since he and I are not able to reproduce this issue in @jafeltra 's branch, we are going to go ahead and merge this into master. @Dtphelan1 if you see the issue in Julia's branch can you add a jira? Thanks!

**Comment by nicoleng12** [comment]
This looks good. All tests pass and the resizing works very nicely.

**Pull request merged**
