### PR TITLE
Medication list pre encounter

### PR DESCRIPTION
**Pull request by gregquinn2001**
JIRA 801 (Pre-encounter should include a list of current medications)
JIRA 822 (TabularListVisualizer should use full width in pre-encounter)
JIRA 824 (#PR, #ER, and #HER2 show up in context tray when fracture is selected as condition)

Added a new test case to verify no medications section in targeted data panel for post-encounter but that there is one in pre-encounter.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X ] Manually tested in Chrome
- [X ] Manually tested in IE

**Documentation**

- [X ] This pull request describes why these changes were made
- [X ] Recognizes any potential shortcomings/bugs in the description 
- [N/A ] Cheat sheet is updated
- [N/A ] Demo script is updated 
- [N/A ] Documentation on Wiki has been updated 
- [N/A ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [N/A ] Note parser has been updated if structured phrases change

**Code Quality**

- [X ] 4-space indents - convert any tabs to spaces
- [X ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X ] Code is commented

**Tests**

- [X ] Existing tests passed
- [N/A ] Added UI tests for slim mode 
- [X ] Added UI tests for full mode
- [N/A ] Added backend tests for fluxNotes code
- [N/A ] Added note parser examples to test new functionality

## Reviewer 1: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Noranda

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
The list of medications looks good!

[NN1] - In pre-encounter view for the medications, the row lines don't extend all the way to include the end date. Can you extend the lines so it covers the whole row? The same goes for the rows in procedures

[NN2] - In pre-encounter mode, the end date for medications is lighter in color than the start date. Can you make the color the same for both? If you decide to go with the darker color, can you also make the dates in procedures a darker color too?

Using the full width in pre-encounter mode makes the view much nicer than before. Nice job!

#PR, #ER, and #HER2 no longer show up in the context tray when the condition is not 'invasive ductal carcinoma of breast'

Tests all pass.

[NN3] - Can you remove the commented out lines of code in your test? Console logs, etc.

Tested manually in IE and chrome and it works.

**Comment by gregquinn2001** [comment]
NN1 solved

**Comment by gregquinn2001** [comment]
Also fixed name of PR and HER2 tests to say PR and HER2 respectively instead of all saying ER

**Comment by nicoleng12** [comment]
All the changes look good!

**Comment by noranda** [comment]
This PR looks great, but I have a UI concern.

[NB1] - When showing medications, we show 2 dates without any context. Common sense may tell us that the first date is the starting date and the second date is the end date, but we should make this explicit. I would recommend doing what we did in Procedures where we add "to" between the 2 dates.

Also, just for my understanding, are we displaying end dates based on when the prescription runs out? I notice we have a future date in the example. How do we determine which of these medications the patient is currently taking?

**Comment by gregquinn2001** [comment]
Good questions. I'll look into resolving the first part. As for the 2nd, I can look at it some, but it may have to wait for some clinician input in terms of what they want

**Comment by gregquinn2001** [comment]
I tried resolving NB1. Let me know what you think @noranda  and anyone else who can review!

**Comment by noranda** [comment]
Looks great!

**Comment by nicoleng12** [comment]
That fix looks good! Just one small thing. In the console we get a warning: 
image

can you add a unique key to get rid of the warning?

**Comment by gregquinn2001** [comment]
oops. I'll fix that. thanks

**Comment by gregquinn2001** [comment]
fixed now

**Pull request merged**
