### PR TITLE
Added tests to cover PersonOfRecord and Entry methods on Patient

### PR DESCRIPTION
**Pull request by mtorchio**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

This pull request adds several tests to the Patient. Some tests already existed, but these provide better coverage of the use of Entry and PersonOfRecord objects by Patient. There may be more advanced tests that could be done on these methods as well. The purpose of this is to prepare for switching to the use of the object model, and providing regression tests to ensure we can identify where things break during that conversion.

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [X] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [N/A] Cheat sheet is updated
- [N/A] Demo script is updated 
- [N/A] Documentation on Wiki has been updated 
- [N/A] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [N/A] Note parser has been updated if structured phrases change

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [N/A] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [X] Existing tests passed
- [N/A] Added UI tests for slim mode 
- [N/A] Added UI tests for full mode
- [X] Added backend tests for fluxNotes code
- [N/A] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] These tests need to compare the hard-coded patient json data to the patient method result. they should not hard-code expected results in the test.
[GQ2] Also, the patient is changing for the new object model and these tests reflect the old patient. These tests should be created within the new branch instead and should go against the methods of PatientRecord.

Finally, Nicole is working on 659 which is to add tests for patient. If you were doing these, you should have assigned yourself to that subtask so we didn't have 2 people working on the same thing...

Sorry but I think our communication as a team broke down here. We should discuss this in the retrospective perhaps?

**Comment by nicoleng12** [comment]
@mtorchio what is the current progress on the fixes for this branch?

**Comment by mtorchio** [comment]
@nicoleng12 I am now working on fixes to Patient.test.js in the deserialize-to-new-object-model branch, and no longer working in this branch. These tests are against the old Patient and can be discarded.

When I changed that file to reference the new PatientRecord, all of the tests began to fail. I have been going through each of them, removing tests that no longer make sense, and fixing the test or PatientRecord to get them passing.

For example, PatientRecord.getMostRecentEntryFromList() was always returning null because it was referencing o.lastUpdateDate, which doesn't exist on the objects we are using. Changing that to o._entryInfo._lastUpdateDate corrected the return values.

When that is ready, for each of these testing subtasks have you been branching off the deserialize-to-new-object-model branch and creating a pull request to merge the test's branch into deserialize-to-new-object-model?

**Comment by gregquinn2001** [comment]
can we just delete this branch then and close the pull request?

**Comment by jafeltra** [comment]
@mtorchio To try to answer your question about branching and submitting pull requests for each subtask, all the subtasks that I have completed have been merged into the deserialize-to-new-object-model branch. I believe that is true for all the other subtasks that others have worked on as well. You should be able to do the same (just add your changes directly into that branch), but I would confirm that with @gregquinn2001.

**Comment by gregquinn2001** [comment]
Sorry, i missed the question. Thanks @jafeltra and yes I agree with what Julia said. Just push your changes @mtorchio  for the tests directly to the deserialize to new object model branch ASAP! We need to merge this branch and that's the last missing piece.

**Comment by Dtphelan1** [comment]
@mtorchio  @gregquinn2001  @jafeltra  Is this branch dead now that deserialzie-obj-model is done?

**Comment by mtorchio** [comment]
Yes, this branch is OBE.

**Comment by Dtphelan1** [comment]
Closing this as it's OBE after merging deserialize-obj-model branch

**Pull request closed without merging**
