### PR TITLE
new SHR-based patient model / Patient object / condition summary metadata

### PR DESCRIPTION
**Pull request by gregquinn2001**
initial commit of new patient model using SHR JSON instance with abstraction on top for accessing - Patient. Updated summary and timeline to use it and updated summary to use metadata defined in json per condition

### CODE REVIEW

**Comment by nicoleng12** [comment]
Adding back in the paper background to the editor panel makes the editor panel look consistent with the other 2 panels (and preserve the look and feel of full app). 

Insertion of data summary items into the editor works. I noticed, however, that there is an error when the user inserts the shortcut then inserts items from the summary panel. Inserted items from the summary panel turn into structured fields. 
image

Should we make a jira issue for this?

**Comment by gregquinn2001** [comment]
I actually saw that too, but thought it would get solved once we can hook up the disable insertion when in a structured field. Dylan's changes making sure slate selection sync's with html focus will also help. I didn't create a jira. If after we implement that functionality fully, it still has issues, then we should enter them. I'll create a jira to implement the disabling of insertion buttons but I think it has to wait for your and Dylan's stuff to get merged with me stuff.

**Comment by Dtphelan1** [comment]
I agree that it should probably wait until everything is merged together before we start knocking out those small, related tasks; they might be solved in the process of or as a product of fixing something in the existing tasks.

**Comment by nicoleng12** [comment]
Ok based on your comments (Greg and Dylan) then this branch looks good to me

**Comment by gregquinn2001** [comment]
Moved the hard coded metadata describing how to summarize a condition into a separate class (still hard coded for now though).
Also add focus to the transform chain after insertText for inserting summary items into editor. this resolves jira 213 so I pulled that into sprint

**Comment by Dtphelan1** [comment]
Nice touch regarding the focus function.

**Comment by gregquinn2001** [comment]
thanks! it's nice when things are that easy!

**Pull request merged**
