### PR TITLE
Lab visualizer

### PR DESCRIPTION
**Pull request by Dtphelan1**
Addresses JIRA 765

Adds initial LineChartLabVisualizer. Also modifies hardcodedpatient to follow style guidelines re: spaces and indentation size. Adds multiple libraries we've to the project: 
- d3-scale (for scaling one domain to another)
- d3-array (for array operations)
- d3-time (for time constants)
- recharts (for visualizations)

Issues already noted on JIRA: 
- Chart doesn't resize (JIRA 811)
- There are no banded regions ala mockups (JIRA 835)

Haven't added tests yet because we're reevaluating the criteria for what needs tests vs. what doesn't, and we don't have a backend directory for visualizer tests yet. If people feel strongly that something should be tested, I'd be happy to add them!  

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [N/A] Cheat sheet is updated
- [N/A] Demo script is updated 
- [N/A] Documentation on Wiki has been updated 
- [x] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [N/A] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [N/A] Added UI tests for slim mode 
- [N/A] Added UI tests for full mode`
- [N/A] Added backend tests for fluxNotes code
- [N/A] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Very cool! Issues:
[GQ1] The graph needs to be labelled as White Blood Cell counts or whatever it is
[GQ2] We need to indicate the units used on the Y axis somehow
[GQ3] Can we format the dates on the X axis to match all the other dates in the UI? 25 Nov 2017 for example.

**Comment by jafeltra** [comment]
This looks really good to me! I haven't noticed any issues besides the limitations you noted in the description and in Jira tasks and what Greg just mentioned. Maybe if we align the dates on the X axis (GQ3), we can have the date in the tooltip match that format as well. Once Greg's issues have been addressed, I can approve this!

**Comment by nicoleng12** [comment]
This looks really good. I like the annotations when you hover over data points on the graphs. I agree with @gregquinn2001 and @jafeltra . Fixing those issues should be good for this to merge

**Comment by gregquinn2001** [comment]
For GQ2, perhaps as part of the title for GQ1 (which I assume will look like subsection titles basically, we could just put the y axis units in parenthesis?) Otherwise, we can jira this one for now.

**Comment by Dtphelan1** [comment]
[GQ4] - Originally I used the code, but tried to rely on displayText to establish the sectionName as a single point of truth when it comes to the name of the yVariable and the value by which you filter on the labResults. I'll change it back to code now, and maybe we can talk about that more in person; something tells me it won't be a simple discussion to have online. 
[GQ2] - I can make it a part of the title! Sounds good to me.

**Comment by gregquinn2001** [comment]
For [GQ2], if it's easy, even better would be to put the title before the graph like:

White Blood Cell Count (2.12 10^9/L as of 2 Jan 2018)

to show the most recent value like Edwin's mock-ups. If too much or disagree, please disregard and stick with:

White Blood Cell Count (10^9/L)

**Comment by gregquinn2001** [comment]
For [GQ4] We can talk via Skype if you want. I don't want to be a blocker!

**Comment by Dtphelan1** [comment]
If you have a minute to talk on Skype then yeah! We can talk abotu GQ2 and GQ4

**Comment by Dtphelan1** [comment]
Initial fixes for GQ1-4 are in! Let me know what you think!

**Pull request merged**
