### PR TITLE
Dr Name Placement & SVG Fill/Padding Fixes

### PR DESCRIPTION
**Pull request by Dtphelan1**
Addresses ASCOP-DCP 1000 and 1004 

1000: [Full] Move Dr name underneath Flux Notes Logo
1004: [Full] Fix SVG icon for table vs narrative

Based on conversations I've had with Greg and Edwin I've removed the button that used to wrap the Dr. name as the padding made it difficult to to couch underneath the FluxNotes title. Other than that everything else was pretty straightforward. 

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] **N/A** Cheat sheet is updated
- [ ] **N/A** Demo script is updated 
- [ ] **N/A** Documentation on Wiki has been updated 
- [ ] **N/A** Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] **N/A** Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] **N/A** Added UI tests for slim mode 
- [ ] **N/A** Added UI tests for full mode
- [ ] **N/A** Added backend tests for fluxNotes code
- [ ] **N/A** Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This just needs to be rebased, but I don't think there should be any conflicts.

**Comment by nicoleng12** [comment]
Looks good Dyaln! All tests pass. Once this is rebased i'll merge it

**Comment by Dtphelan1** [comment]
All set with the rebase! @nicoleng12 let me know if we're all good on merging.

**Comment by nicoleng12** [comment]
Will do! Just re running tests

**Pull request merged**
