### PR TITLE
loading a note back into editor no longer updates patient

### PR DESCRIPTION
**Pull request by gregquinn2001**
Loading a note back into editor no longer updates patient at all. It should have done that when it was created!

Cleaned up ShortcutManager code. Also updated clinical notes in hard coded patient to match structured data better. Took some hash tags out to support data curation scenarios later where corresponding structured data didn't exist.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [ ] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [ ] 4-space indents - convert any tabs to spaces
- [ ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added UI tests for slim mode 
- [ ] Added UI tests for full mode
- [ ] Added backend tests for fluxNotes code
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
Nice! Loading notes no longer updates patient data, which is reflected in the targeted data panel. If the staging information is missing, loading an existing note with staging information should not update the patient info, which this branch takes care of. Nice job! 

[NN1] You mentioned that you took some hashtags out in the notes, but I noticed that in the first note (the August 2, 2015 one) that there are still hashtags for the disease status info

**Comment by gregquinn2001** [comment]
Yes NN1 is correct, but the progression structured data reflects that value if you look in hard coded patient json or on the timeline on that date. It represents data already in the patient record which is the only case # expressions should stay.

**Comment by nicoleng12** [comment]
If the progression data is in hard coded patient, why does it display as missing in the summary section?

**Comment by gregquinn2001** [comment]
because it is not recent by any means! At least that's what the idea was. If we don't have something within x months, then it's basically missing. We should get a new progression assessment.

**Comment by gregquinn2001** [comment]
In the actual progression section it will show all data we have. In the summary, we only want recent data

**Comment by nicoleng12** [comment]
I see, ok that makes sense. This looks good to me! All tests pass

**Comment by Dtphelan1** [comment]
This looks good to me. All tests pass with no issue.

**Pull request merged**
