### PR TITLE
Added support for multiple conditions in the context tray

### PR DESCRIPTION
**Pull request by noranda**
# Added support for multiple conditions in the context tray

Selecting a condition will now show a section for the selected condition in the context tray with child context sections below. Selecting a second condition will add it to the context tray below the first condition with its child context sections below instead. Added arrows to denote collapsing of context sections not currently displayed. New functionality matches designs from `shr_fluxnotes_concept_v12.6_selected_concepts_screens.pdf` section 4.

Added UI tests. Tested in Chrome and IE. Other minor changes due to code and editor whitespace cleanup.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter: Noranda

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- Cheat sheet is updated
- Demo script is updated 
- Documentation on Wiki has been updated 
- Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- Added UI tests for slim mode 
- [x] Added UI tests for full mode
- Added backend tests for fluxNotes code
- Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
This looks good to me! Checked tests on my end and everything seems to pass! Implemented feature matches mockups. Great work!

**Comment by jafeltra** [comment]
This looks good to me! The context tray looks really good and very organized now!  All the tests pass as well.

One thing I noticed is that clicking on a condition in the context tray does not actually change the context back to that condition. I'm not sure if that's something that we even want, but its not something that needs to be addressed in this pull request.

**Comment by jafeltra** [comment]
This just needs to be rebased!

**Comment by noranda** [comment]
Rebased!

**Pull request merged**
