### PR TITLE
Full mode shortcut defaulting

### PR DESCRIPTION
**Pull request by laclark22**
Updated shortcut infrastructure to support default being in full mode and added default as of date for disease status. Added as of date to be displayed in summary only after status is set. Eliminated inserter shortcut base class, moving logic into insert value directly. 

## Submitters: Greg Quinn and Laura Clark

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] Cheat sheet is updated
- [x] Demo script is updated 
- [x] Documentation on Wiki has been updated 
- [x] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] Added UI tests for slim mode 
- [x] Added UI tests for full mode
- [x] Added backend tests for fluxNotes code
- [x] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Test by adding ductal carcinoma condition to note then choose #disease status then choose a status. The progression status and as of rows in the summary on the left should get updated to show selected status and have today's date in as of row. Add #as of then #date and choose a date other than today. The as of row in summary should change. Delete the date from the note and the as of row should go back to showing today's date.

**Comment by gregquinn2001** [comment]
I'm going to rebase this again now and add as of date to narrative given the narrative pull request was merged.

**Comment by gregquinn2001** [comment]
Parsing is broken after rebase. I need to fix it so please hold off on reviewing this pull request until I post another note. Sorry!

**Comment by gregquinn2001** [comment]
ok. parsing is fixed. Please review!

**Comment by jafeltra** [comment]
This looks good to me. I like the new wording for the as of date in the narrative. Both narrative and tabular components update with the default date, then a chosen date, then back to the default date, like Greg described to test it. All the tests pass as well.

**Comment by gregquinn2001** [comment]
Thanks @jafeltra. We need 1 more reviewer please!

**Pull request merged**
