### PR TITLE
Piecemeal styling fixes 12-11-2017

### PR DESCRIPTION
**Pull request by Dtphelan1**
Remedy some scattered styling issues introduced with most recent features, including:
- Changing the styling of the clinical notes sort dropdown to match the color palette established by other dropdowns.
- Removing row and col divs from the data buttons – they just need some padding.
- Removing padding from New Note button.
- Clinical note list in pre-encounter mode only need col-sm-3.
- The page has y-overflow that might be resulting from panel-heights that are too large.
- Improve styling of summary-sections so narrative and tabular components have the same padding – right now they don't and this results in different, uglier minimaps in pre-encounter mode
- Padding on the clinical-notes button in post-encounter mode. 

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- Cheat sheet is updated
- Demo script is updated 
- Documentation on Wiki has been updated 
- Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- Added UI tests for slim mode 
- Added UI tests for full mode
- Added backend tests for fluxNotes code
- Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Started looking at first sub-task and noticed that our note sort dropdown doesn't have all the options from mockup. Would you mind just updating the list of options to match: Most recent, Least recent, Author type, Specialty, Encounter, Note
(from concepts v11.9 screen 4.1)

**Comment by Dtphelan1** [comment]
Taken care of!

**Comment by danlee1025** [comment]
[DL1] At 100% zoom level on Chrome, when I go from post-encounter to pre-encounter mode, the items on the timeline are in the wrong place.  I can replicate this on IE at varying zoom levels and this does not seem to be happening on master.

**Comment by Dtphelan1** [comment]
(I know we talked in person, but for record keeping) I'm not able to reproduce this on my end... Weird. Anyone else?

**Comment by nicoleng12** [comment]
I cannot reproduce [DL1]. Neither can @jafeltra

**Comment by nicoleng12** [comment]
All the tests pass. Everything looks good. Nice job! What should we do about DL1? It seems like only @danlee1025 sees this issue?

**Comment by gregquinn2001** [comment]
I did see it as well when they asked me to reproduce it.

**Comment by gregquinn2001** [comment]
Maybe Dylan should go back to each commit in history until problem stops happening on Dan's machine and then hopefully we can figure out what's causing it. Or maybe Dan can try that. I noticed Dylan did commits for each subtask it looks like.

**Comment by danlee1025** [comment]
I will try this out later tonight.

**Comment by danlee1025** [comment]
After deleting everything and doing a clean install, the problem seems to be gone...  So not too sure what the problem was.  @gregquinn2001 Do you want to see if the problem still persists on your end or are we good to merge?

**Comment by gregquinn2001** [comment]
Same for me. I tried deleting node_modules and re-installing and the problem still existed. Like Dan, when I deleting entire flux local repo and re-cloned, the problem went away. Issue is now not reproducible and we can go ahead and merge this.

**Comment by Dtphelan1** [comment]
So @daniellee1025 Is this PR good?

**Comment by Dtphelan1** [comment]
So @daniellee1025 we good to Approve?

**Comment by gregquinn2001** [comment]
Yes, I think you can approve and merge if you're ok

**Pull request merged**
