### PR TITLE
Targeted data control component2

### PR DESCRIPTION
**Pull request by mtorchio**
This creates the TargetedDataControl as described in the mockups. It contains the Condition dropdown and the encounter/workflow selector which is now also a dropdown. Buttons have been added to switch between narrative and tabular data display - but they currently just update state and do not change how the data is displayed.
SummaryPanel has been renamed to TargetedDataPanel and DataSummaryPanel has been renamed to TargetedDataSubpanel. 
The SVGs are displayed very small in IE. We may want to discuss the layout and whether these dropdowns should be in the left panel or should be moved back to the top, it's a little jarring to have one panel affect the whole app. A test has been added for the new buttons.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [X] Manually tested in IE  - tiny SVGs

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [**N/A**] Cheat sheet is updated
- [**N/A**] Demo script is updated 
- [**N/A**] Documentation on Wiki has been updated 
- [**N/A**] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [**N/A**] Note parser has been updated if structured phrases change

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [ ] Existing tests passed
- [**N/A**] Added UI tests for slim mode 
- [X] Added UI tests for full mode
- [**N/A**] Added backend tests for fluxNotes code
- [**N/A**] Added note parser examples to test new functionality

## Reviewer 1: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
@mtorchio it looks like travis is saying CI tests failed and this branch also has conflicts and should be rebased. Is there an issue with rebasing?

**Comment by mtorchio** [comment]
Julia and I are working through the Travis error, the new test is failing. I don't see an issue with rebasing.

**Comment by Dtphelan1** [comment]
[DP1] We need to add PropTypes to the TargetedDataControl.

**Comment by gregquinn2001** [comment]
Good catch @Dtphelan1 ! Still having nightmares about adding them to everything?

**Comment by jafeltra** [comment]
I worked with Dylan to get some of the outstanding tasks on this branch. It has been rebased, the PropTypes have been added, the new test was fixed and now passes, and the icons were resized. Let me know if anyone else sees anything to change.

**Comment by nicoleng12** [comment]
It looks like all of the issues have been addressed. I tested this manually in chrome and IE and it looks good. All the tests pass

**Pull request merged**
