### PR TITLE
Declarative shortcuts

### PR DESCRIPTION
**Pull request by gregquinn2001**
JIRA 634. This pull request finally incorporates declarative shortcuts into Flux Notes. Both slim and full modes are driven from the declarative style shortcuts. The shortcuts.json file in the shortcuts folder specifies all shortcuts. Note that FullApp instances defined in the AppManager now accept a list of shortcuts to support. If the list is empty, all enabled shortcuts are supported (shortcuts can be disabled within the shortcuts.json file by specifying a property of "disabled" : true.

The shortcuts.json file format is specified (needs work probably) on wiki at https://github.com/standardhealth/flux/wiki/Declarative-Shortcut-Format

All backend tests pass. UI tests are broken in my environment.
(error Could not open cafile: EISDIR: illegal operation on a directory, read
error Could not open cafile: EISDIR: illegal operation on a directory, read
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.)

NOTE: removed app menu as part of this pull request as well.

** Please test out slim and full mode and see if you can find issues with this update! Report them using our syntax of initials following by number so we can address each issue **

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [X] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [N/A] Cheat sheet is updated
- [N/A] Demo script is updated 
- [X] Documentation on Wiki has been updated 
- [X] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [X] Note parser has been updated if structured phrases change

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [X] Existing tests passed
- [N/A] Added UI tests for slim mode 
- [N/A] Added UI tests for full mode
- [?] Added backend tests for fluxNotes code
- [N/A] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
[DP1] Autocomplete of "#clinical trial" or "#deceased" doesn't work, instead logs error "Shortcut.jsx:24 Uncaught TypeError: Primitive shortcut has no prefix character"

[DP2] Autocomplete Menu of available shortcuts doesn't update with updated contexts.

**Comment by gregquinn2001** [comment]
Thanks Dylan! I'll start looking at these. I guess my regression failed to catch those.

**Comment by gregquinn2001** [comment]
Can you give an example of what you mean by DP2?

**Comment by gregquinn2001** [comment]
I pushed a fix for DP1

**Comment by Dtphelan1** [comment]
Sounds great! Also it looks like some of the other failed tests in slim mode come from case sensitivity and date formatting. Specifically: 

[DP3] In Slim Mode, UI tests of Clinical Trial fail because the clinical trial name is lowercased when shown in the copyButton, whereas tests expect them to match the case of the text in the button.

[DP4] In Slim Mode, UI tests of Clinical Trial and Deceased fail because the date is converted to a different string format when shown in the copyButton, whereas tests expect them to match the case of the format in the text-box.

**Comment by Dtphelan1** [comment]
As for DP2, in full mode I type "@condition" and select "Invasive...". I don't get "#toxicity" or "#staging" to populate the autocomplete dropdown when I type "#"

**Comment by gregquinn2001** [comment]
Thanks on DP2. I reproduced. Also, thanks on DP3 and DP4. I did get the ui tests to run finally but haven't had a chance to look at results. Appreciate all the testing help!

**Comment by Dtphelan1** [comment]
No problem! Happy to help. let me know if there is anything else I can do to help!

**Comment by jafeltra** [comment]
[JA1] When I choose the fracture condition, it still displays the shortcuts for breast cancer (#staging, #toxicity, etc).

**Comment by jafeltra** [comment]
[JA2] Copy and pasting gives me the following error:  Uncaught TypeError: shortcut.determineText is not a function

To reproduce, type @condition #staging and copy and past the text.

If you try typing @condition #staging #T0, I get another error (Uncaught TypeError: Cannot read property 'getValueObject' of undefined), but I think that is probably related to the first error.

[JA3] In slim mode, on the disease status shortcut, I think we want the copy button to default to just "#disease status". Right now it defaults to having all the "?"s where data is missing.

**Comment by gregquinn2001** [comment]
Thanks Julia!

**Comment by jafeltra** [comment]
Let me know if I can help look into some of the issues identified!

**Comment by gregquinn2001** [comment]
I know the problem with JA1. It's something I left out for now in implementation but have in the json already. JA2 may require more implementation. What about looking into what's causing JA3 if you have time?

**Comment by jafeltra** [comment]
Sure sounds good!

**Comment by gregquinn2001** [comment]
DP2 fix is pushed.

**Comment by nicoleng12** [comment]
The wiki documentation is very thorough. Looks good Greg!

[NN1] - In slim mode, picking a date via the date picker for clinical trial or deceased and then deleting it results in an error. The date is not removed from the copy button. For example, in slim mode, go to the deceased form. In the date picker select November 5. Then click back in the date and delete it. November 5 remains in the copy button and the console displays the following error:

image

This does not happen in the master branch

**Comment by gregquinn2001** [comment]
Thanks @nicoleng12 . One of my recent changes must have introduced this. Thanks!

**Comment by gregquinn2001** [comment]
NN1 fixed

**Comment by gregquinn2001** [comment]
DP3 and DP4 both resolved.

**Comment by gregquinn2001** [comment]
JA1 fixed and the wiki documentation updated.

**Comment by gregquinn2001** [comment]
JA3 resolved. Just JA2 outstanding.

**Comment by gregquinn2001** [comment]
JA2 is resolved. I also brought in latest master and fixed some issues on clinical trial form. Please test as much as you can. I will too. We can start over with numbering if you want.

**Comment by danlee1025** [comment]
Good job, all tests passing.

[DL1]  @Stage inserter is showing up in the context panel even though stage is missing.
[DL2]  Not sure if this is a problem, but in Slim Mode on the Disease Status tab the as of date is in the form of "#14 Nov 2017" instead of "#11/14/2017".

**Comment by gregquinn2001** [comment]
Good finds! I'll fix 'em. thanks. DL2 is a problem

**Comment by gregquinn2001** [comment]
thanks @Dtphelan1 !

**Comment by nicoleng12** [comment]
All of the previous issues have been fixed. Nice!

One really small thing:

[NN1] - When you click on the Disease Status tab, the copy button shows #disease status #as of <today's date>. In master, only when a button is selected does the 'as of' date show up. By default it only shows #disease status. I don't have a strong preference either way but just noting that this is different from master

**Comment by gregquinn2001** [comment]
@nicoleng12 . I was aware of NN1 and left it as I have no easy way to fix it right now. Since as of date has a value, it is displayed. If people feel strongly that we need to fix that, I can look into it. IMO, in either case the structured phrase is really incomplete and not very useful...

**Comment by gregquinn2001** [comment]
thanks for reviewing @nicoleng12 !

**Comment by nicoleng12** [comment]
@gregquinn2001 I think it's fine to just leave it the way you have it now

**Comment by jafeltra** [comment]
[JA1] This is really small, but should there be spaces between multiple rationales listed for disease progression?

Other than that, all the other comments seem to be addressed, except for DL1, and I couldn't find anything else! Nice job!

**Comment by gregquinn2001** [comment]
Thanks @jafeltra ! I'll resolve JA1 after DL1.

**Comment by gregquinn2001** [comment]
DL1 is resolved. Now just JA1. Thanks for the thorough testing everyone!

**Comment by gregquinn2001** [comment]
JA1 resolved. I need to get one last review from someone before this can be merged!

Thanks!

**Comment by nicoleng12** [comment]
Everything looks good! All issues have been addressed. I'll merge this as soon as the travis tests pass

**Comment by gregquinn2001** [comment]
Thank you @nicoleng12 ! Thank you everyone for all your support on this one. Big milestone to get this in!

**Pull request merged**
