### PR TITLE
Reuse visualizers+Inserters in Name/Value Pair tables

### PR DESCRIPTION
**Pull request by gregquinn2001**
Covers JIRA 870 and 862. Medication tabular and name value pair tabular now both reuse the column tabular visualizer now.

Also, please check out how the space is being used between pre-encounter and post-encounter within the targeted data panel. I didn't quite do what 862 said to do, but I think it uses the space better.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [ ] 4-space indents - convert any tabs to spaces
- [ ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [ ] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added UI tests for slim mode 
- [ ] Added UI tests for full mode
- [ ] Added backend tests for fluxNotes code
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
[DP1] The styling of the the sub-section header (e.g. "Current Diagnosis", "Recent Lab Results") blends in with the Name in name-value pairs. Adding Italics/bolding makes them sufficiently distinct IMO. 
[DP2] (actually my fault) The CSS used to underline text with red/blue lines doesn't color them in IE. 

I have styling changes on my end that fix both of these. Let me know if you would me to push them/see them first!

**Comment by gregquinn2001** [comment]
For DP1, I had checked the heading styling and I didn't change it. I think the difference really is that the left-hand items in name/value pair lists were actually gray text (so lighter than the headers). Should we try to replicate what it was or just make the subsection headings darker?

Definitely push DP2, but let's discuss the above before pushing DP1 change.

**Comment by mtorchio** [comment]
This looks good to me. I agree with Dylan that the headers mentioned in DP1 are not visually distinctive enough. It's very nice to see that giant switch statement going away. One minor thing - is there a reason that the old values in MedicationRangeChartVisualizer.jsx are kept in comments? Is there a chance we will need to go back to the originals?

All the tests pass.

**Comment by nicoleng12** [comment]
All the tests pass. This looks good! I like how you're using the space in pre-encounter mode. I like that you can grab medication information by object now instead of having to know what index it is in the array.

[NN1] - Can you remove the commented out code in SummaryMetadata.jsx in the getItemListForMedications method?

**Comment by Dtphelan1** [comment]
I could try both out and send screenshots to compare. I hear you though. it's just a product of the changes made to the name-value pair styling.

**Comment by gregquinn2001** [comment]
push your DP1 solution and let me know. I'll take a look. I'm guessing it will be fine and easier to just go with that maybe.

**Comment by gregquinn2001** [comment]
I'm resoling NN1 and MT1 now

**Comment by Dtphelan1** [comment]
What'd I do... -_-

**Comment by gregquinn2001** [comment]
Dylan your comment said to "remove styling changes" but I want to be clear that I did not make styling changes for the subheadings or the underlines.

NN1 and MT1 resolved

**Comment by Dtphelan1** [comment]
My comment was in reference to a previous commit I had made, not your changes.

**Comment by gregquinn2001** [comment]
@Dtphelan1 why did you remove the sub-heading styling changes?

**Comment by Dtphelan1** [comment]
Timeline: 
1. I made both changes, commiting them to my local branch without pushing
2. You told me to wait on DP1 and keep DP2
3. I made a second commit removing DP1.
4. I pushed both commits.
5. You told me to commit DP1 and DP2.
6. You told me for the record you didn't change the styling
7. I responded to that explaining what my commit did/was in reference to.
8. You asked for why.
9. I made this timeline as an explanation. 
10. I put back DP1 (coming soon to a theater near you)

**Comment by Dtphelan1** [comment]
That should take care of that 😄 👍

**Comment by gregquinn2001** [comment]
lol. ok. I'll check out the DP1 solution. You're happy with it?

**Comment by Dtphelan1** [comment]
I think it looks pretty good. Might be a little hefty; greying out the name-value pair names might be less ink-intensive in the application which could be a plus. Let me know what you think. Also @noranda lmk if you have any opininons.

**Comment by gregquinn2001** [comment]
I say we go with it. It's certainly better than it was! @nicoleng12 or @mtorchio can you do a quick review of styling changes for subheadings?

**Pull request merged**
