### PR TITLE
Progression date assessed

### PR DESCRIPTION
**Pull request by jafeltra**
The goal of this pull request is to add the "#as of #13 Sep 2017" string automatically to the copy line in slim mode. There is no way to adjust the as of date. The "#as of" shortcut is not created yet either. Although it does have some functionality in full mode, the goal of this task is not to have that fully functioning yet, so not everything that will be needed there is implemented.

### CODE REVIEW

**Comment by mtorchio** [comment]
Ran and tested it, the date is present and can be copied with the rest of the progression text. Looks good to me.

**Comment by gregquinn2001** [comment]
This looks great. A few nits (only the first is really part of slim mode anyways):

Please rename updateDateForProgression to be updateAsOfDateForProgression.
DateCreator.getShortcutType should return "#date"
DateCreator.validateInCurrentContext should just return an empty list since DateCreator is generic
DateCreator.getDescription should just return "a date" I guess. It's not always today's date.

**Comment by gregquinn2001** [comment]
In ProgressionCreator the attribute is just "date" right now. Let's change that to "asof" or "asofdate"

**Comment by jafeltra** [comment]
Ah these are all good points that I didn't think to incoporate after deciding that Date was going to be generic. I can fix them! For the DateCreator.validateInCurrentContext comment, should the method be returning an empty list for errors? I'm just clarifying what you meant. Also, I'm thinking that eventually this should be changed to check if the context is "asOf" or "referenceDate", but since those don't exist yet, I won't add them. I can add a note though if that sounds right.

**Comment by gregquinn2001** [comment]
Yeah sorry. good clarification. DateCreator.validateInCurrentContext should always just return an empty list of errors because it is valid in any context. The user can always specify a date. the parent context will receive that date and it will in turn pass it on to its parent context knowing which attribute to put it in. I think that should work. So, the DateCreator will not know anything about who can be its parent as it is a generic way to enter a date in a note as structured data. So I don't think it should ever check if its parent is asOf or referenceDate. Does that make more sense?

**Comment by jafeltra** [comment]
Thanks for the clarification. I think that makes sense. I'll leave it as an empty list of errors.

**Comment by jafeltra** [comment]
I just updated the pull request based on Greg's comments. Let me know if any other updates are neeed!

**Pull request merged**
