### PR TITLE
Unify yarn and package

### PR DESCRIPTION
**Pull request by Dtphelan1**
yarn.lock and package.json are now synced to install the same files.

### CODE REVIEW

**Comment by gregquinn2001** [comment]
do we need to clean up yarn.lock though? It seems to have a lot of dependencies in there and I'm thinking some of them are not used??

**Comment by Dtphelan1** [comment]
This is a good point, though I think most of those dependencies you're seeing in yarn.lock are just the child dependencies of packages we do use. There were a few packages in our package.json file that we don't use anymore, though. So good catch!

**Comment by gregquinn2001** [comment]
ok great. good to clean it out while you're in there. thanks!

**Comment by gregquinn2001** [comment]
Note that you didn't add anyone as reviewers so that may be why no one else has looked at this. I added myself as a reviewer

**Comment by Dtphelan1** [comment]
whoops....

**Pull request merged**
