### PR TITLE
Refactored Patient Summary

### PR DESCRIPTION
**Pull request by noranda**
# Refactored Patient Summary

### Changes Made:
* Upgraded packages for material-ui select box to use design-improved `Select` component:
   * `material-ui` and `material-ui-icons` upgraded from `1.0.0-beta.5` to `1.0.0-beta.16`
   * `react-router-dom` upgraded from `4.1.1` to `4.2.2` (dependency for newly upgraded `material-ui`)
* Implemented new design for patient summary panel:
   * Changed app font family CSS to `font-family: "Open Sans", Roboto, Arial, sans-serif;` to match designs
   * Added higher resolution patient image
   * Added new component called `PatientSummaryPanel`
   * Moved `SummaryHeader` into new component and styled to match design
   * Moved `ConditionSelection` into new component and styled to match design
      * Changed side arrow selection to a select dropdown menu
      * Clicking on a condition will set the `condition` state in the `FullApp` component, which is then passed to the `DataSummaryPanel` component to update the problem summary 
   * Added new `Event` section which has 3 buttons: `Pre-encounter`, `Encounter`, and `Treatment`
      * Clicking on a button will set the `event` state in the `FullApp` component
      * Currently the `event` state is not being used, but as the design becomes further implemented, this is ready to be hooked up
* Improved code quality:
   * Converted 2-space tabs to 4-space in files I worked in
   * Converted function binding in render or the constructor to use public class field syntax
   * Restructured render functions to be more readable by breaking down into smaller functions where applicable, in files I worked in
   * Removed unnecessary whitespace (auto-removed by my editor)
* Wrote tests:
   * Wrote a unit test to test `setFullAppState` which can be passed to children components and be used to set the "global" full app state until we add Redux
   * Wrote several UI acceptance tests to verify buttons and select dropdown work as expected

_Pull requests into Flux require the following: Submitter and reviewer should ✅ when done. For items that are not-applicable, note it's not-applicable (N/A) and ✅._

# Submitter: Noranda 

### Documentation

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] **N/A** Cheat sheet is updated
- [x] Demo script is updated 
- [x] **N/A** Documentation on Wiki has been updated 
- [x] **N/A** Additional technical components and libraries are documented and added to wiki as needed

### NoteParser

- [x] **N/A** Note parser has been updated if structured phrases change

### Code Quality

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

### Tests

- [x] Existing tests passed 
- [x] **N/A** Added UI tests for slim mode 
- [x] Added UI tests for full mode
- [x] **N/A** Added backend tests for fluxNotes code
- [x] **N/A** Added note parser examples to test new functionality

# Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

# Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

# Preview:

patient-summary-panel

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Noranda, can you please indicate what drove upgrading the material UI and react-router-dom components in your description?

**Comment by noranda** [comment]
@gregquinn2001 Updated!

**Comment by gregquinn2001** [comment]
This looks really good except one of the UI tests is failing on both browsers for me (Patient Mode - Timeline). That test should not have been affected by your changes really as you didn't change the timeline, right? Does it fail when you run the ui tests?

**Comment by gregquinn2001** [comment]
Also, @noranda can you re-baseline to master so this is ready to merge?

**Comment by gregquinn2001** [comment]
@noranda can you run yarn install and see if your yarn.lock changes again? Mine is different after running yarn install

**Comment by nicoleng12** [comment]
This looks really good! The timeline test also fails for me but this is a problem I've been having (it works when i run the tests on my large monitors but not on my laptop screen, no matter how much I zoom out) so it's not related to this branch.

Just a couple of small things:
[NN1] - When I click on the condition button to select a different condition, the grey highlight covers both options instead of just the one my mouse is hovering over. For example if I have fracture selected then i want to choose invasive ductal carcinoma of breast, the grey highlight still covers fracture but then also covers the newly hovered on item

[NN2] - The styling for the condition selector is slightly different from the selector for @condition. The selector for @condition uses a blue highlight. I don't know if it's important or not if the 2 selectors have the same style or are different because one is a shortcut.

**Comment by noranda** [comment]
@gregquinn2001:
* Tests: Yes, I had a lot of issues getting tests to pass consistently, not sure why. All tests that were inconsistently failing (ie. would fail on one run, the pass on the next with nothing changed) were unrelated to files I changed.
* Rebase: Done.
* Yarn.lock: Ran again after rebase and no changes.

**Comment by gregquinn2001** [comment]
Good catch on NN1. I didn't notice that the first time!
NN2 is also a good one. @noranda if the @condition autocomplete should change to match what you did, just log a new jira. If yours should change to match @condition autocomplete styling then I think it should be resolved before merging. Make sense?

**Comment by gregquinn2001** [comment]
@nicoleng12  did your yarn.lock change after running yarn install?

**Comment by nicoleng12** [comment]
@gregquinn2001 Yes, when i pulled this branch and did a yarn install i believe it changed because in my yarn.lock file i have material-ui version 1.0.0-beta.16, not 15

**Comment by noranda** [comment]
@nicoleng12:
* **NN1**: I believe this is expected behavior for the `Select` material-ui component used. The selected option is highlighted by default so you know what's already selected. Hovering also has the same style. If desired, I can make these two styles different (maybe have the hover option blue?).
* **NN2**: I see the different styles. In the notes, since nothing is really selected, it will be slightly different. I can change the styles in the select dropdown to more closely match (gray for selected, blue for hover, decrease top/bottom margins). Sound good?
* Yarn.lock: The version should be `1.0.0-beta.15`. I will update the `package.json` file.

**Comment by nicoleng12** [comment]
@noranda 

- NN1: Ah good point. You're right. When we have more conditions this will be more obvious. I'm ok leaving this as is then. I don't have a strong opinion about changing the hover color option

- NN2: Based on your comment from NN1 I see now why it would be different because it's not already selected. I think just making the selected/hover colors the same for both selectors (whether you decide grey or blue) is fine and making the margins similar is good. Again these are really nit picky comments I made so not super important but nice to have :)

**Comment by noranda** [comment]
Updated styles. My mistake on the `material-ui` version. Current version is `1.0.0-beta.16` (the beta 15 version is for `material-ui-icons`.

Note: I'm getting failed test in the timeline again, and can't seem to get it to pass like I could before. I will look into it further.

**Comment by nicoleng12** [comment]
Looks great!

**Pull request merged**
