### PR TITLE
support customizing the targeted data panel based on the task

### PR DESCRIPTION
**Pull request by gregquinn2001**
JIRA 802. Support customizing the targeted data panel based on the task (pre-encounter, encounter, post-encounter right now)

Added a Medications name/value pair section that only appears in pre-encounter for now. This should become a list type once that data type is supported (another jira being done in this sprint). When changing to pre-encounter you should see the medications section in Targeted Data Panel but when in post-encounter you should not.

Also resolves JIRA 821. Removes grade 2 from patina site toxicity.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X ] Manually tested in Chrome
- [X ] Manually tested in IE

**Documentation**

- [X ] This pull request describes why these changes were made
- [X ] Recognizes any potential shortcomings/bugs in the description 
- [N/A ] Cheat sheet is updated
- [N/A ] Demo script is updated 
- [N/A ] Documentation on Wiki has been updated 
- [N/A ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [N/A ] Note parser has been updated if structured phrases change

**Code Quality**

- [X ] 4-space indents - convert any tabs to spaces
- [X ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X ] Code is commented

**Tests**

- [X ] Existing tests passed
- [N/A ] Added UI tests for slim mode 
- [X ] Added UI tests for full mode
- [X ] Added backend tests for fluxNotes code
- [X ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
not quite yet. Once Mike finishes his task (756) to support the List data type, I'll finish 801 using that.

**Comment by jafeltra** [comment]
This looks good! The medications appear in pre-encounter but not post-encounter.

One really small thing I noticed is that I don't think we need to pass the clinicalEvent prop on to the TargetedDataSection. We probably don't need to fix this now, but it might help keep our props cleaner.

Also, nice quick fix on the grade 2 change!

**Comment by gregquinn2001** [comment]
@jafeltra I pass it into the section so they can customize based on the clinical event/task as well. It's not used by any sections right now

**Comment by jafeltra** [comment]
Okay. That makes sense. This looks good to me then! All the tests pass.

**Pull request merged**
