### PR TITLE
Local copy of patient entries in TargetedDataSubPanel (TDSP)

### PR DESCRIPTION
**Pull request by Dtphelan1**
Addresses JIRA-1024: [Full] Initial implementation of TargetedDataSubpanel's copy of patient object, using that to determine return value of "shouldComponentUpdate"

In addition to storing a local copy of the patient entries (sans notes) I had to store a few other key elements that play into whether or not the TDSP, including: 
- The current clincal event (visualizers and minimap update when the number 
- The number of signed entries (as values get signed, their underlines in visualizers change)
- Whether or not the TDSP isWide (width changes the way some visualizers like tabular and bandedlinechart are displayed)

Compare the performance of typing text in our editor with that of fluxnotes.org or master. Let me know if there are any cases I've missed for updates, if you're not seeing the performance boost, if you'd like anything in my code to change or if there's anything else on your mind! 

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- **N/A** Cheat sheet is updated
- **N/A** Demo script is updated 
- **N/A** Documentation on Wiki has been updated 
- **N/A** Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- **N/A** Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- **N/A** Added UI tests for slim mode 
- **N/A** Added UI tests for full mode
- **N/A** Added backend tests for fluxNotes code
- **N/A** Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This looks good! I definitely see an improvement in the performance when you type! I haven't found anything that isn't updating, besides the one thing you fixed even before a JA1! 💯 I am getting one test to fail when I run all the tests, which didn't used to happen. I've tested it myself and run it using `test.only` and it passes, so I'm not sure why that's happening or if it's happening for anyone else. This is the test: `Entering disease status information updates the data in the targeted data panel to indicate that the disease status information is unsigned 1) AssertionError: expected false to be truthy`.

**Comment by danlee1025** [comment]
Everything looks good and all tests pass on my end.  So much faster!

Just two things:
* Should we use arrow functions in the reduce functions?
* Lines 73 and 80, can you add a space between the 'if' and '('?

**Comment by Dtphelan1** [comment]
I'll take your approval as a yes 😄

**Comment by jafeltra** [comment]
I don't know why that test is failing some times, but it passes now.

**Comment by jafeltra** [comment]
Just waiting for Travis.

**Pull request merged**
