### PR TITLE
Narrative support

### PR DESCRIPTION
**Pull request by gregquinn2001**
JIRA 750. Add narrative support to target data panel as a visualization component that visualizes name value pair data types in metadata that have a narrative property (for now). Later the buttons in the Targeted Data Control will allow switching between narrative and tabular views.

Also changed logic in metadata to show most recent progression as long as it is within 12 months instead of only 6. Also, include date of progression status with status right now. May want to change this to its own name/value pair for as of date in the future though...

NarrativeComponent is name used for new visualization component within Targeted Data Panel. It supports NameValuePairs type in summary metadata. We need to standardize naming for these components.

TODO: (JIRA 743-in progress) Render other types of data. also change how it decides which visualization component to use when multiple (e.g., NameValuePairs): TimelineComponent for Events
TODO: (JIRA 756) Add a List type and a tabular renderer for it for Procedures section. case where left column is data and not just a label

I also created a FluxBreastCancer wrapper class and changed some of the summary metadata methods to take advantage of its simplified form for getting data for the condition.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [X] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [N/A] Cheat sheet is updated
- [not yet] Demo script is updated 
- [N/A] Documentation on Wiki has been updated 
- [N/A] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [N/A] Note parser has been updated if structured phrases change

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [x] Existing tests passed
- [N/A] Added UI tests for slim mode 
- [none] Added UI tests for full mode
- [none] Added backend tests for fluxNotes code
- [N/A] Added note parser examples to test new functionality

## Reviewer 1: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by danlee1025** [comment]
Looks good!

[DL1] Are we planning to standardize visualization components by putting the Component suffix after each of them.  Should we rename DataSummaryTable to TabularComponent?
[DL2] Can we remove the commented lines of code that are no longer going to be used?

**Comment by gregquinn2001** [comment]
For DL1, yes I want to standardize naming as I mention in my pull request description. I want to discuss it more because I'm thinking just a Component suffix isn't enough. I think there should be a reference to the type it supports as well? Maybe it should be NarrativeNameValuePairsComponent and TabularNameValuePairsComponent?

For DL2, I left the commented out line in the summary metadata on purpose because (and I meant to mention this in pull request, we may want to incorporate additional data items that are only used in narrative. Right now I put The patient has <condition> but clinicians may prefer (even though redundant) to put <patient name> is a <age> year old <gender> with <condition>. All that info is in patient summary but mock-ups have it and we really need to get clinician feedback to know right way to go. If we need that info, some of those commented out things would be useful.

**Comment by danlee1025** [comment]
I'm good with DL1, we can discuss later on naming.

On DL2, sounds good on the big commented section in SummaryMetadata.  Can we remove the commented lines where you are taking advantage of the wrapper classes?

[DL3] Is the narrative data supposed to update when we add new data through the editor?

**Comment by gregquinn2001** [comment]
For DL2, I'll remove any lines from changing to wrapper classes.
For DL3, yes it should. Good catch! I'll take a look.

**Comment by gregquinn2001** [comment]
DL2 should be resolved. I removed a lot of commented out code and also improved the use of FluxBreastCancer and eliminated some more methods in patient record.

**Comment by gregquinn2001** [comment]
I can rename components as part of this pull request if you want to discuss and reach consensus on a naming convention. You can then update your component to match before you do a pull request as well.

**Comment by danlee1025** [comment]
Data is updating now!  When's a good time to discuss naming?  Or should we just stick with Component suffix for now until we have more people in the lab?

**Comment by gregquinn2001** [comment]
We can discuss tomorrow after standup? My current preference would be for <name><type>Component where type is NameValuePairs or Events or List so far. We'd have:

TimelineEventsComponent
TabularNameValuePairsComponent
NarrativeNameValuePairsComponent
TabularListComponent (for Procedures or other lists where the left column is data and not just a fixed label)

**Comment by gregquinn2001** [comment]
Components renamed. Please review and approve so we can merge! I'll add above to wiki as well.

**Comment by danlee1025** [comment]
For some statuses the narrative wording sounds a little weird.  e.g. "disease is complete response..."

We may need to change this in slim mode as it has similar wording in the copy content so we may just want to fix this wording in a separate task.

Other than that, everything else looks good!

**Comment by nicoleng12** [comment]
Looks good! I tested it in chrome and IE and it works. All tests pass. DL1, DL2, and DL3 have all been addressed. Removing narrative from meta data for a particular section puts it back into tabular form so code to easily switch between the 2 modes has been set up. I agree with @danlee1025 that the wording is a bit strange but that has always been there and wasn't introduced with this branch so maybe we can just make a separate jira for it?

**Comment by jafeltra** [comment]
This looks really great! I have two really minor things.

[JA1] It looks like FluxBreastCancer.js has tabs instead of spaces in it. Is that something we want to change to line out with our styles?
[JA2] For disease status, if there is no as of date, it just says undefined. Should that be "missing"? Also when I delete the status, it doesn't say missing like it does if you remove the staging. Is that something we want to say missing?

**Comment by gregquinn2001** [comment]
Thanks on JA1! My new computer has notepad++ and I forgot to put setting to replace tabs with spaces. I'll do that now and fix the file that is wrong.

**Comment by gregquinn2001** [comment]
JA1 resolved

**Comment by gregquinn2001** [comment]
For JA2, I'm going to remove that change. Laura's pull request handles this much better.

**Comment by gregquinn2001** [comment]
JA2 resolved.

**Comment by gregquinn2001** [comment]
I'll rebase it now

**Comment by jafeltra** [comment]
Looks good to me! JA1 and JA2 are fixed thanks!

**Comment by jafeltra** [comment]
Since all other comments were addressed, I can merge this in now.

**Pull request merged**
