### PR TITLE
New medications inserter

### PR DESCRIPTION
**Pull request by gregquinn2001**
JIRA 819. Actually added @all medications and @active medications. The first puts all medications whether active or not into the note. The 2nd inserts just medications that the patient is currently taking. The 2nd one should only insert a single medication as the hard coded patient only has 1 active. I shifted that medication so it would be active longer (it was set to end on 1 Jan 2018 in a few days!).

I also cleaned out some comments and added a method to getActiveMedications from patient record.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [ ] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [ ] 4-space indents - convert any tabs to spaces
- [ ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added UI tests for slim mode 
- [ ] Added UI tests for full mode
- [ ] Added backend tests for fluxNotes code
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
This looks good! I have the same comment on this PR as I did for the allergies inserter PR. Depending on what we decide for that PR we should do the same for this PR.

**Comment by gregquinn2001** [comment]
agreed. I think the way it is may be the best we can do right now but open to other ideas!

**Comment by gregquinn2001** [comment]
Added JIRA 829 to support a conditional newline that inserters can use to cause a new line to be inserted if the current insertion point isn't already at the start of a new line. This could be used at the start this inserter's content to put the block of medications on its own lines and not to start at the end of a current line in progress.

**Comment by nicoleng12** [comment]
Since the issue will be covered in jira 829, I approve of the changes made in this branch.

**Pull request merged**
