### PR TITLE
New component notes panel

### PR DESCRIPTION
**Pull request by nicoleng12**
Made a new component called "NotesPanel" that contains FluxNotesEditor and ContextTray components

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- N/A Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
I haven't looked yet of course, but I have a question. Is NotesPanel name the agreed to name? Did you discuss with Julia and/or Dylan?

**Comment by nicoleng12** [comment]
@gregquinn2001  Yes, I spoke with Julia and Dylan and that's the name we came up with for now

**Comment by gregquinn2001** [comment]
ok great! Thanks

**Comment by gregquinn2001** [comment]
This looks pretty good. I am getting some unused vars warnings in console.


C:\working\flux\src\dashboardViews\PostEncounterView.jsx
  3:8  warning  'FluxNotesEditor' is defined but never used  no-unused-vars
  4:8  warning  'ContextTray' is defined but never used      no-unused-vars

? 2 problems (0 errors, 2 warnings)

**Comment by nicoleng12** [comment]
@gregquinn2001 Thanks for the review! Those imports should have been removed in an earlier commit... Can you try re pulling the branch to make sure you have the latest version?

**Comment by gregquinn2001** [comment]
yes, sorry. I pulled and they are gone.

**Comment by nicoleng12** [comment]
Rebased on master

**Pull request merged**
