### PR TITLE
Implement sign button

### PR DESCRIPTION
**Pull request by nicoleng12**
This PR addresses jira 814.
- Added "Sign note" button
- "Sign note" button is displayed on the screen only when the note editor is editable and a note is selected (can't sign a note that is already signed)
- Clicking the "Sign note" button sets the sign attribute on the note to true and closes the note editor
- Signing a note moves an in-progress note from the list of in-progress notes to the list of existing notes (to see this, look at the increase in number on the "View X more more clinical notes" button or in NoteAssistant update the max notes to display from 3 to at least 5 to see the signed note show up in the list)
- Added SecurityManager and UserProfile classes to store the logged in user. The name of the logged in user in the patient control panel and the name of the clinician that is added to a new note now use the name from the user profile
- Added UI test to check that number of in progress notes decreases when the current in-progress note is signed

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- [x] Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
Rebased on master

**Comment by jafeltra** [comment]
This looks good to me. A few things I noticed:

[JA1] I think we should be able to see the note that we just saved. I know this isn't really a bug since it is working correctly with what we have now, but it seems like that would be something we'd want to be able to see in the list. Maybe we could sort the notes chronologically until we implement the "2 more clinical notes" button. Or maybe we could just extend the list to view more notes before adding the button.

[JA2] I'm not sure if this is something we want to change right now, but it seems a little weird that the "Sign note" button doesn't appear until you start typing in a note. I talked to Nicole about this and it's because we don't actually have a note yet so we don't have anything to sign. It just seems a little weird that the only thing that changes when you start typing (and a note is created and selected behind the scenes) is the button appearing. Maybe we need to create a new note when the page loads instead of just when you start typing? I'm not sure.

**Comment by nicoleng12** [comment]
Nice finds! Thanks for reviewing. I addressed JA1. I made a time sorter so that the most recent notes show up on top of the list so that when you sign a note, you will see it in the clinical notes. 

For JA2, what do you think @gregquinn2001 ?

**Comment by nicoleng12** [comment]
After talking with @jafeltra and @gregquinn2001 created a jira for JA2: https://jira.mitre.org/browse/ASCODCP-942

**Comment by jafeltra** [comment]
The change for JA1 looks good! Thanks for making the Jira. All the tests pass. This looks good to me.

**Pull request merged**
