### PR TITLE
Upgraded to material-beta-13

### PR DESCRIPTION
**Pull request by Dtphelan1**
Upgraded to beta 13, changed one thing in Nav, didn't see any other issues. Someone wanna check their machine for  full functionality too?

### CODE REVIEW

**Comment by mtorchio** [comment]
Looks good to me. The only item I noticed was a new warning: 

Warning: Material-UI: the value provided `4` is invalid

**Comment by nicoleng12** [comment]
Everything looks good! I tested both in chrome and in IE as well as ran the unit tests. All the unit tests passed. 

I also see the warning that Torch saw. As he wrote, it happens when you click on the calendar. If the fix is not super straightforward, should we close this request, merge it, and make a jira for the material ui warning?

**Comment by gregquinn2001** [comment]
I would say it makes sense to look into and perhaps understand what's causing the warning. If knowing that, it doesn't affect us, then we can merge this and log a jira to eliminate the warning. If the exploration is taking too long, record what you learned in the JIRA and close it since the task was to explore and only implement if no work was required. Make sense?

**Comment by Dtphelan1** [comment]
That's weird. I'm not getting that warning... When one of you is in the office, I'd like to come over and take a peek! Let me know.

**Comment by laclark22** [comment]
I don't see any warnings when I click on the calendar. Very strange that some of us do and some of us don't...

**Comment by jafeltra** [comment]
So I realized this morning that I forgot to run yarn install, so my testing of this was completely useless and I'm getting the same warning now, and also an error "Uncaught RangeError: Maximum call stack size exceeded". Sorry for not thinking yesterday!

**Comment by Dtphelan1** [comment]
I'm now able to get the bug. It seems like the update has somehow caused a lag in setState for the ContextTray's Tabs. This is a breaking bug, and because of it I don't think we should update our beta. We can revisit the Material ui beta update when we change our Context Tray's UI away from the Tabs and towards the sectioned buttons, but for now it looks like we shouldn't put any more time into this.

**Comment by gregquinn2001** [comment]
Sounds good. Please record what you learned on the JIRA (make sure it says the specific version you were going from and to). You can reference this pull request thread directly from a comment.

**Comment by Dtphelan1** [comment]
Can do!

**Pull request closed without merging**
