### PR TITLE
Publish on structured focus

### PR DESCRIPTION
**Pull request by Dtphelan1**
From task 96: Publish events or change state for when editor within staging structured field.

When the staging structured field is initiated in MyEditor, trigger a state change in App that cascades down to the right panel, switching the templates panel to a staging form entry.

Upon blur of focus on the Staging structured field, trigger a state change in App that cascades down to the right panel, switching the current structured field form entry back to templates staging

When focused on the staging structured field in MyEditor, trigger a state change in App that cascades down to the right panel, switching the templates panel to a staging form entry.

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Why the rename of WithinStructuredField to StructuredField? I like the old name better as that more indicates it's meaning. It doesn't just hold a structured field but instead references the structured field we are currently within where null means we are not within one right now.

**Comment by Dtphelan1** [comment]
I didn't understand the metaphor of being 'within', because the information is held at the global App level. In that way, I didn't find the naming intuitive. If you feel strongly about having a preposition or adj in front of StructuredField, since it's not the structured field and we might want to disambiguate, we can talk about potential naming candidates or we can revert to the old name. Either way, your call.

**Comment by gregquinn2001** [comment]
Also, why the removal of the structured field entered and exited events in favor of key status event? Again, I'm not sure the name change is intuitive so let's discuss your thinking.

**Comment by gregquinn2001** [comment]
Let's discuss. Call me via skype when you get a few minutes. It's not my call. It's a discussion.

**Comment by gregquinn2001** [comment]
When I click to after the structured field and start typing it never sends an exit event for the structured field.

**Comment by gregquinn2001** [comment]
If I enter the values it successfully sends exit event and then when I left arrow back into the structured field, I get enter event and then when I right arrow out I get exit event correctly so maybe it's only when the structured field hasn't been fully entered that the exit isn't working...

**Comment by Dtphelan1** [comment]
I've made appropriate changes in light of the discussion above. 

As for your newest bug, that sounds like an implementation issue that hopefully we can dodge in the demos. I think capturing it as a jira issue is probably a good idea for now.

**Comment by gregquinn2001** [comment]
sounds good. if you can capture it and move it to the top of backlog to make sure we review it next backlog grooming meeting that would be great

**Comment by Dtphelan1** [comment]
Added bug to the top of the backlog. Feel free to merge if the branch is looking good.

**Pull request merged**
