### PR TITLE
Fhir data source

### PR DESCRIPTION
**Pull request by danlee1025**
JIRA-806

- Added path /p3 to use FHIRApiDataSource.
- FHIRApiDataSource currently uses a hardcodedFHIRPatient but there is code commented out to make the REST Call to SyntheticMASS.
- In PatientRecord, there is a fromFHIR function that will loop through the FHIR JSON and create the correct SHR Objects.
      - There is a FHIRMapper that is mapping the FHIR entry types to SHR entry types.
- Manually added fromFHIR functions to many SHR Object Classes to parse correctly.
- Currently only able to parse PersonOfRecord and Condition entries so it will look very similar to the Fracture condition with a condition name and diagnosis date.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
-  Cheat sheet is updated
-  Demo script is updated 
-  Documentation on Wiki has been updated 
-  Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

-  Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
-  Added UI tests for slim mode 
-  Added UI tests for full mode
-  Added backend tests for fluxNotes code
-  Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
This looks good Dan. The code looks good and navigating to /p3 shows the app using data from the fhir data source. 

[NN1] - We have backend tests testing the other data sources. Should some tests be added to test the fhir data source?

**Comment by gregquinn2001** [comment]
For NN1, I would like to hold off. Let's way for the auto-generated fromFHIR methods if that's ok. I'm concerned things will change. If people feel strongly, maybe we can meet in the middle and add a few tests to start.

**Comment by danlee1025** [comment]
[GQ1] I can do that.  I was actually going to ask you that but forgot.  It seems to work pretty well.

**Comment by jafeltra** [comment]
This looks really good to me! I talked to Dan about maybe moving the `get time` method he added to a Flux wrapper, which Dan agreed with. I tested this with both the hardcoded json and uncommenting the REST call to syntheticMASS and it worked both ways. The application renders and the diagnosis dates for each condition appear on the timeline.

**Comment by danlee1025** [comment]
@gregquinn2001 for NN1, Nicole is just suggesting adding backend tests for the FHIRApiDataSource like we do for the other dataaccess sources.  I agree we should probably hold off on tests for the fromFHIR functions on the object models.

**Comment by gregquinn2001** [comment]
Oh ok. Sorry. Sounds good then! I just don't want to go nuts adding a lot more tests right now.

**Comment by gregquinn2001** [comment]
The addition of FluxConditon is a little problematic as you discovered. You had to add the same method in 2 places even though they are in the same class hierarchy... This is something we've avoided until now and one of the reasons why I wanted to revisit our model

**Comment by danlee1025** [comment]
NN1 should be good now and branch has been rebased.

**Comment by nicoleng12** [comment]
Awesome! Testing now

**Comment by nicoleng12** [comment]
Ok after you commented out that one test because of the proxy issue, the tests pass. Looks good! Once this passes the travis tests I'll merge it

**Pull request merged**
