### PR TITLE
right panel now shows shortcuts when no patient

### PR DESCRIPTION
**Pull request by gregquinn2001**
stays the same when patient

### CODE REVIEW

**Comment by nicoleng12** [comment]
Switching between patient and no patient view toggles what "templates" or "shortcuts" are displayed. This looks good to me to merge

**Comment by Dtphelan1** [comment]
Minor concern: The header is for templates. Is that what we are providing? Or are we providing the inline-helper shortcuts? If they're templates, I'm good to merge; if not, we should change this header.

**Comment by gregquinn2001** [comment]
Yeah Nicole and I discussed this as well. We're not sure yet if it will be shortcuts and templates (where shortcuts can be a simple template) or just shortcuts. Didn't know what to label that panel. Obviously right now it shows only shortcuts for structured data items so maybe we should just re-label it with "Data Items" or "Structured Data Items" although I've been thinking we'd avoid the term "structured data" in the UI. We can't use "Summary Item" because we have no summary in no patient mode... So, I was a little at a loss for what to name it and whether it would include templates still so I just left it as is...

**Comment by gregquinn2001** [comment]
Should I just change the label to "Data Items" for now and merge?

**Comment by Dtphelan1** [comment]
Yeah that works for now!

**Comment by Dtphelan1** [comment]
After that I'd be happy to merge

**Pull request merged**
