### PR TITLE
Deserialize to new object model

### PR DESCRIPTION
**Pull request by gregquinn2001**
For JIRA 585. deserialize json content to the new SHR object model and then use that to drive Flux Note lite and full. Note parsing also is functional.

Can as many people as possible pull down this branch and test out slim, full, and parsing? Please report any problem as part of discussion for this pull request and assign an identifier for each issue using your initials and number. Before submitting an issue, please review others already reported to avoid duplicates if possible. I probably will not be able to fix issues until tonight so if you can grab one, please do. Just post to the chat that you are going to work on issue XY# so no one else starts working on it. Be careful too when pushing. We need to make sure we stay coordinated through this discussion.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [X] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [X] Cheat sheet is updated
- [X] Demo script is updated 
- [X] Documentation on Wiki has been updated 
- [X] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [X] Note parser has been updated if structured phrases change

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [X] Existing tests passed
- [X] Added UI tests for slim mode 
- [X] Added UI tests for full mode
- [X] Added backend tests for fluxNotes code
- [X] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by danlee1025** [comment]
[DL1] When changing the selected condition to Fracture in Full Mode, procedures not associated with Fracture show up in the Problem Summary.
[DL2] Might be related to DL1, but the procedures and medications not related to Fracture show up in the Timeline.

**Comment by gregquinn2001** [comment]
Are DL1 and DL2 issues on master as well?

**Comment by danlee1025** [comment]
Checking now...

**Comment by danlee1025** [comment]
Fine on master.

**Comment by gregquinn2001** [comment]
ok we should fix then! Thanks for checking

**Comment by danlee1025** [comment]
I will look into DL1 and DL2.

**Comment by danlee1025** [comment]
DL1 and DL2 should be good now, the filter functions were not selecting the correct property from the new object model.

**Comment by danlee1025** [comment]
[DL3] Full App UI tests are failing.

**Comment by danlee1025** [comment]
Worked with Julia to fix DL3.

**Comment by jafeltra** [comment]
This is exciting that all of this is working! I noticed a few small things. I can look into them tomorrow, unless others know of fixes right away.

[JA1] Adding all staging values and then deleting them doesn't remove the stage. I think this leaves the @stage button in the context tray and in the summary table.
[JA2 ?] This is more of a question. There seem to be more events on the timeline for disease status. Is that expected? I haven't looked into why that is at all yet.

Also, I noticed the Shortcuts.json file is in this PR. Does this PR include the declarative shortcut changes as well?

**Comment by gregquinn2001** [comment]
Thanks Julia! For JA2, I don't think it was working quite right before and it actually got fixed. We can certainly compare the hardcoded json patient to make sure the number of progresssion values is the same though. We also fixed the summary view of the progression which is why I pulled in that JIRA (596) and we can close it when we merge this pull request I think.

**Comment by gregquinn2001** [comment]
Wow on JA3! That should be deleted. I'll take care of that right now!

**Comment by gregquinn2001** [comment]
thanks @noranda!

**Comment by Dtphelan1** [comment]
[DP 1] Unable to delete "#as of" keyword from "#disease status" after adding and deleting the "#date" entered.

**Comment by danlee1025** [comment]
ProgressionAsOfDateCreator.jsx
In deserialize-to-new-object-model branch:
```
shouldBeInContext() {
        let asOf = this.parentContext.getAttributeValue("asOf");
        return (Lang.isNull(asOf) || asOf === false);
    }
```
In master:
```
    shouldBeInContext() {
        return (Lang.isNull(this.parentContext.progression.asOfDate));
    }
```

If I change it back to how it is in master, we are able to delete the "as of" keyword again.  I don't know enough of why this change was made so I was hoping others would comment.

**Comment by jafeltra** [comment]
I think the problem is that the new change needs to use `.getAttributeValue('asOfDate')`. `asOf` and `asOfDate` are two different attributes, even though the naming is so similar. But `asOfDate` should tell you if the date was actually set or not, not just if the #as of shortcut was entered. I'm not sure why the change was made though. If there was a reason for it, maybe it would be best to also change ProgressionReferenceDateCreator.jsx to do something similar in the shouldBeInContext() method, although I think both ways achieve the same thing.

**Comment by jafeltra** [comment]
And @gregquinn2001  thanks for clarifying JA2 and fixing JA3! I'll look into JA1 now.

**Comment by danlee1025** [comment]
Worked with Julia on the latest commit which should fix JA1.

**Comment by Dtphelan1** [comment]
Great so we just need feeback from @gregquinn2001 to figure out whether or not the change from "asOfDate" to "asOf" is motivated by some intentional reason, and if _so_ we need to discuss why it isn't working as-is.

**Comment by mtorchio** [comment]
I have tried to break this, and apart from the asOfDate problem, I haven't found any additional issues.

**Comment by gregquinn2001** [comment]
Hi all, sorry I'm just getting on-line. I think putting it back seems right. I'm not sure how it got changed to what it did. Somehow (like the shortcuts.json file that Julia noticed originally), some changes from the declarative-shortcuts branch crept into this branch; that's my bad definitely. Dan, please put it back and then do some thorough testing of the #progression shortcut in both slim, full, and parsing including adding #as of and then deleting it then adding #as of then a date then deleting. Also try adding it using right context subpanel, by typing it, and by autocomplete menu and then in each case make sure it can be deleted afterwards. Thanks and tomorrow if something like this comes up, send me a text saying I'm a blocker! You can even call me bad names in said text!

**Comment by gregquinn2001** [comment]
So after you fix this and test it, let's get this merged! Nice work!

**Comment by danlee1025** [comment]
Fix is in.  All backend and UI tests pass.  I did some testing on Full and the note parser.  Not really too sure how to test as of date in Slim, but the Disease Status tab is working fine.  I did discover some errors though which is also happening in master.  When we type a note and switch the pane to pre-encounter and then back to post-encounter, the editor is cleared and messes up the disease status data on the summary panel.(I will log this into JIRA)

I tried to rebase with master earlier and it was pretty hellish... Are we OK with just merging master into this branch?

**Comment by gregquinn2001** [comment]
As of date isn't used in slim mode so it should just show #as of #<today's date> in the copy button always.

Thanks for logging bugs you found that exist in master!

I'm fine with merging or maybe we can make it a team sport and use the tool that Nicole has to help us through it...

**Comment by Dtphelan1** [comment]
So I've played around with master on my local repo to check that the merge wouldn't break something long-term. The merge to master works fine. Furthermore, I've checked how our feature branches would fare when rebasing onto the master that has the deserialize branch merged in.: 
- remove-paper: No issue
- patina_customization_of_slim: Small issue that would be easy to fix
- update-summary-section: No issue
- declarative-shortcuts: Looks like there's a fair amount here that will require careful rebasing. 

Other than that, the remaining branches seem to be branches that we built into the deserialze-to-new-obj-model branch, so I didn't bother checking them. That said, these branches should be deleted once this is all said and done. 

With all of that noted, I'm going to merge this branch in. Congrats team, we did it!

**Pull request merged**
