### PR TITLE
Context portal styling

### PR DESCRIPTION
**Pull request by Dtphelan1**
In this PR: 
- Improved styling of the context menu,
- Improved the positioning function for the context menu based on code in slate-suggestions,
- Improved styling of selected elements in other autocomplete menus to match the new menu styling,
- On files I touched in accomplishing these tasks, I aligned styling with recent style guidelines. Changes include: 
    - Replacing tabs with spaces.
    - Consistently use 4 spaces to indent.
    - Unified use of arrow functions in class definitions to ensure the 'this' keyword means the same thing across functions. 
    - In ContextPortal I refactored the keydown function, removed duplicate reference to context being stored in ContextPortal's state, and fixed selectedIndex to be stored in the component's state.

### CODE REVIEW

**Comment by nicoleng12** [comment]
The styling looks good! 

[NN1] Can you make sure you have the latest master pulled into your branch? (sorry i made a direct commit to master to update the link on the landing page. It should not break anything)

[NN2] When I go to patient mode and click the @CONDITION button, nothing happens. There is no display with options for the user to select. The following is displayed in the console:
image

**Comment by jafeltra** [comment]
The styling looks good to me! I noticed the same two things Nicole did though.

**Comment by Dtphelan1** [comment]
Thanks y'all. I'm looking into the NN2, and am taking care of NN1 now!

**Comment by Dtphelan1** [comment]
Rebased to address NN1 and fixed NN2 y addressing dropdown placement issues. Let me know if there's anything else you see!

**Comment by nicoleng12** [comment]
NN1 and NN2 have been fixed. Looks good on my end

**Pull request merged**
