### PR TITLE
Style lite-mode shortcut formList 

### PR DESCRIPTION
**Pull request by Dtphelan1**
The main purpose of this PR is to unify the styling of the lite-mode shortcuts dropdown with Edwin's mockups. This involved making some new css for slimApp, making FullApp's css more specific to impact just FullApp components and removing some unnecessary classNames. It also suppresses warnings from an earlier push.

Edit: Dropdown was a misnomer; the PR modifies the styling of lite-mode formList on the left hand side

### CODE REVIEW

**Comment by gregquinn2001** [comment]
I don't understand I guess. what drop-downs exactly did you style? Do you mean the grade dropdown under toxicity and the progression status dropdown under progression? If so, why wouldn't the styling of those apply in full patient mode when they are shown on the right side?

**Comment by gregquinn2001** [comment]
Also, I don't think we should have a search bar at all. We only have 2 shortcuts. Let's either just remove the dummy search bar or at least not include it if the number of shortcuts is less than 10 or something?

**Comment by gregquinn2001** [comment]
We have a jira to implement the search already in our product backlog BTW

**Comment by gregquinn2001** [comment]
should we clean up the console.log messages or are you thinking we may need them for some near future work?

**Comment by nicoleng12** [comment]
Nice job on restyling Flux Notes Lite. LOVE the styling and how it more closely aligns with the mockups. Nice cleanup of warnings. I agree with Greg about the search bar. Can we hide that unless there are a lot of shortcuts in the menu?

**Comment by Dtphelan1** [comment]
Dropdown was a misnomer. I restyled the list of shortcuts in no-patient mode. 

Sure we can hide the search for now. We wanted to align closely with the Mockups so I did the whole deal. If we want to bring the search back in when we implement the search functionality, we can do it then. 

I can drop the console logs.

**Pull request merged**
