### PR TITLE
Added links to cheat sheets on the respective pages in no patient mod…

### PR DESCRIPTION
**Pull request by mtorchio**
…e. Also split up the PDF into separate PDFs for each stuctured phrase

Reviews of styling, spacing, and wording are welcome.

### CODE REVIEW

**Comment by jafeltra** [comment]
Actually, this is really small, but it might look nice to have the line you added about more detail with another break before that way it is a little more spaced out? But I don't feel super strongly about this, so I'm fine with either way!

**Comment by gregquinn2001** [comment]
I like the idea of an extra blank line as well. Also, can we change the text to flow with the rest of the form better? Maybe something like:
"Based on your selections below, the copy button at the bottom will copy a formatted phrase to paste in your EHR." The 'formatted phrase" portion could be the link to the progression or toxicity description document.

**Comment by nicoleng12** [comment]
Looks good. I agree with Julia and Greg's comments. If you can address the following I think it should be good:

[NN1] - rebase your branch to have the latest version of master (Greg and Julia's pull requests were merged into master)

[JA1] - add space between description and the line that has the pdf link

[GQ1] - Change the text to: "Based on your selections below, the copy button at the bottom will copy a formatted phrase to paste in your EHR." The 'formatted phrase" portion could be the link to the progression or toxicity description document.

**Comment by mtorchio** [comment]
I've addressed the items above:
[NN1] this branch is rebased
[JA1] added another space
[GQ1] changed the text

If someone else could re-review this, I'd appreciate it!

**Comment by gregquinn2001** [comment]
looks good.

**Pull request merged**
