### PR TITLE
Timeline summary integration

### PR DESCRIPTION
**Pull request by Dtphelan1**
Incorporate timeline into summary view. Major changes in this branch include: 
- Background color change from grey to white 
- Documentation of a new proposed approach to how we display our visual components within FluxNotes. This will hopefully help us be more careful about how we talk about various parts of our application.
- Addition of new component type "Panel", the specifics of which are expounded on in `Architecture of Visual Components.md`. 
- The addition of the isWide flag to Timeline props; this allows the timeline to display more time when it has more space and vice versa. Motivation for this flag was the breakdown of 'react-calendar-timeline' when it was trying to condense too many events into too little space (i.e. it was breaking when it was being displayed in post-encounter mode.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] **N/A** Cheat sheet is updated
- [x] **N/A** Demo script is updated 
- [x] Documentation on Wiki has been updated 
- [x] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] **N/A** Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] **N/A** Added UI tests for slim mode 
- [x] **N/A** Added UI tests for full mode
- [x] **N/A** Added backend tests for fluxNotes code
- [x] **N/A** Added note parser examples to test new functionality

## Reviewer 1: Julia

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Are you leaving the heading above the timeline section (collection?) within the summary view to Nicole to implement?

**Comment by jafeltra** [comment]
I have a quick question about the naming. So right now, do we have a "Summary Panel" which contains a "Summary Section" and a "Timeline Section"? I just want to make sure I understand what you outlined.

**Comment by Dtphelan1** [comment]
Yes, that’s right. The old components haven’t been renamed according to the new ontology because I wanted to clear it with everyone before touching files.   
  
  
  

  
  

  
  
>

**Comment by jafeltra** [comment]
Thanks! I just wanted to make sure I understood it in the way that you meant it. I think that the naming makes sense to me!

**Comment by nicoleng12** [comment]
@gregquinn2001 the labels I'm working with are in Data Summary Panel, not summary panel which is the parent that contains data summary panel and the time. So no, I don't have a header for Timeline. Where should this be set?

This looks really good Dylan. Tested it in IE and chrome and it works. All tests pass.

Just one thing. Can you attach the image that you made that illustrates the architecture of visual components? It looks like it's a file on your desktop. I'm a little confused on the hierarchy but I think seeing a picture would make it more clear. So for example is the view post-encounter, the panel is the summary panel, the patient summary and timeline are sections? Then what would you call the groupings within the patient summary section which groups data into identification, address, and current diagnosis?

**Comment by Dtphelan1** [comment]
Just fixed the photo issue and added headings. So that should resolve the points made by @nicoleng12  and @gregquinn2001.

**Comment by Dtphelan1** [comment]
Re the groups within a section: I've avoided providing a term for these groupings, because I didn't think there would be a generic category of components for that grouping. If you have one you would suggest, that sounds great; but at that level the conversations usually become sufficiently pinpointed enough to avoid the ambiguity we were struggling with the other day.

**Comment by gregquinn2001** [comment]
[GQ2] documentation describing our naming of visual components within our app should be on the wiki and not in git.  Also, please don't call it architecture. It's just naming conventions for visual components right?
[GQ3] Also, I think the picture's box defining Section is a bit confusing. A section should always have a section heading and it may have subheadings. It looks right now like all the tabular stuff would be a section and then the timeline would be a section. 
[GQ4] Can the timeline be a middle section or does it have to be the last one? The mockups show it as the 2nd section out of about 7 or 8 (but which sections are showing can be customized). It looks right now like we just put the timeline component after the summary table component. We need the summary metadata to introduce the concept of a section component  and sections can have a position attribute (indicating their ordering) and a visible attribute (indicating whether they are currently included in the summary). The metadata should specify the SummaryTable component (or like it) for tabular sections and the SummaryTimeline component for the Timeline section. Make sense?

**Comment by gregquinn2001** [comment]
[GQ5] Also, there are no sections within the editor panel or its right context area. The right context area should be included as part of the editor panel actually as well. They are a package deal. You add the Editor panel and get the editor including its header area and the context options on the right.

**Comment by Dtphelan1** [comment]
[GQ1] I've put it in git for review; the plan was always to move it to the wiki after it was approve. \\
[GQ2] Long term, yes, we will continue making modifications to the summary panel in terms of a) what sections we display, b) their order, etc.... I agree that summary metadata sounds like the right place for that. I didn't  think that should be done in this task thought because a) until this PR goes in we don't have a canonical nomenclature for sections yet, b) we don't know what those other sections will contain yet as we have no mockups for them. 
[GQ4/5] That's something to capture in JIRA. I'll capture that, as well as a few other modifications that need to be done in terms of restructuring and renaming files. But I don't see that as a part of this task.

**Comment by gregquinn2001** [comment]
@Dtphelan1  let's discuss these. I don't think we should be pushing all of these off. Do you have time to talk through these after standup?

Let's move the documentation content to the wiki and remove from git now though. they can be reviewed on the wiki just fine.

**Comment by Dtphelan1** [comment]
Sure.

**Comment by jafeltra** [comment]
This looks really good to me Dylan. The headers you added in look good. The changes you made to the code make sense to me in terms of some slight restructuring of components. I tested the app in Chrome and everything seems to be working. All the tests pass as well, including the timeline test.

**Comment by gregquinn2001** [comment]
You decided to not include the terms "Summary Section" and "Summary Component"? I can see either way. It would be nice to define them, but it's summary panel specific and may create confusion???

**Comment by Dtphelan1** [comment]
Clarified the terms more carefully. Let me know if these new summary panel terms work!

**Comment by nicoleng12** [comment]
This looks good!

**Pull request merged**
