### PR TITLE
Narrative component handling missing data

### PR DESCRIPTION
**Pull request by danlee1025**
- Changed narrative property in SummaryMetadata to be an array of sentence objects.
    - Each sentence object can have these properties:
             - defaultTemplate(required):  Default template to use
             - dataMissingTemplate(optional): Template to use if all data in useDataMissingTemplateCriteria is null.
             - useDataMissingTemplateCriteria(optional): Data that should be checked to determine if dataMissingTemplate should be used.

- NarrativeNameValuePairsVisualizer now parses through each sentence object and determines which template to use.
- Progression items do not show up on timeline unless status is set.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- Cheat sheet is updated
- Demo script is updated 
- Documentation on Wiki has been updated 
- Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

-  Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- Added UI tests for slim mode 
- Added UI tests for full mode
- Added backend tests for fluxNotes code
- Added note parser examples to test new functionality

## Reviewer 1: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
[NN1] - When we are missing progression status it says in the narrative "No recent progression status". If I wasn't familiar with the project, my first thought would be to look for a progression status button on the right context tray but we have "disease status" instead, which is a bit confusing because of the inconsistency. Should we make the missing text say "No recent disease status" to be consistent?

**Comment by danlee1025** [comment]
That sounds good to me to stay consistent.  Are we OK with "No recent lab results" for the missing text for the lab result sentence?  I could change both texts if we want something different.

**Comment by nicoleng12** [comment]
@danlee1025 I think "No recent lab results" is fine for now. I don't know what we would change it to

**Comment by nicoleng12** [comment]
NN1 has been addressed. The missing text looks good and it updates correctly as the data is entered. Code looks good and is well commented. Adding in the use of templates makes it easy to add missing text for other pieces of data as it gets added to the narrative view. All tests pass. Nice job!

**Comment by gregquinn2001** [comment]
[GQ1] No recent progression status sounds good, but it should be underlined to indicate there is missing information!

**Comment by danlee1025** [comment]
For GQ1, do we want the whole sentence underlined?

**Comment by gregquinn2001** [comment]
That's probably easiest for you to implement but maybe just "disease status" would be better. For right now, feel free to make the whole sentence underlined but maybe add a jira to improve on that and allow just a portion to be marked as missing based on mark-up in the template maybe...

**Comment by Dtphelan1** [comment]
Have @gregquinn2001's questions been addressed?

**Pull request merged**
