### PR TITLE
Shortcuts add additional entries

### PR DESCRIPTION
**Pull request by danlee1025**
This PR addresses JIRA-1040.

This fixes the issue where loading a note containing a CreatorBase shortcut(e.g. #staging, #disease status) caused creation of new entries on the patient.  What should be happening is retrieving the existing entry that was previously created and making changes on that entry.

Changes:
* Added bracket notation to CreatorBase shortcuts
  * In the brackets of CreatorBase shortcuts, a JSON object containing the entryId of the object is included so that we can add additional properties in the future.
  * Example: #disease status[[{"entryId": 1001}]]
*  Moved shortcut specific logic out of FluxNotesEditor.jsx and StructuredFieldPlugin.jsx and into the shortcut classes.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
-  Recognizes any potential shortcomings/bugs in the description 
-  Cheat sheet is updated
-  Demo script is updated 
-  Documentation on Wiki has been updated 
-  Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

-  Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
-  Added UI tests for slim mode 
-  Added UI tests for full mode
-  Added backend tests for fluxNotes code
-  Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] Not sure if this is a problem on master too.... if so, we can jira issue it
New Note
@condition and choose Invasive Ductal Carcinoma of the Breast
#disease status #stable #imaging #pathology

switch to note list on right and click on an existing note
click on in-progress note on right side to re-open it
imaging now appears twice in summary on left under Rationale

**Comment by danlee1025** [comment]
For GQ1, this is not a problem on master.  Can you make sure to have the most up to date commits on my branch and do a re-build? I had seen this problem earlier and thought I had fixed it.  If it is still occurring I will investigate but I was not able to reproduce the issue.

**Comment by gregquinn2001** [comment]
I have the latest. I did a pull and tried it again and it still exhibits the same problem. Did you do the exact sequence that I did? Maybe you're doing something a little differently? If you can't reproduce it, I can show you via skype tomorrow.

**Comment by danlee1025** [comment]
Yeah I think I'm following the same steps but you can show me tomorrow.

**Comment by danlee1025** [comment]
@gregquinn2001 I found it, I was using the suggestion portal to choose my rationales instead of typing it out.

**Comment by gregquinn2001** [comment]
Looks good!

**Comment by nicoleng12** [comment]
Everything looks good so far. I don't see the bug anymore. I just need to run the tests. Was GQ1 turned into a jira issue?

**Comment by danlee1025** [comment]
GQ1 has been fixed.

**Pull request merged**
