### PR TITLE
Shortcut adt

### PR DESCRIPTION
**Pull request by Dtphelan1**
As a subtask of task 291: No patient mode should replace editor with data item viewer and "Done" button

We've got a base class for shortcuts, an class called progression that extends shortcut, and in slimapp we have a shortcut tracked in state and a function for changing that shortcut. 

This feels a bit quick for my usual turnover, but it feels like this might be all we need in terms of modeling for task 291.  Can you all take a look at this, and if it looks good let's merge it to master; if you see things missing or think of other functions/features to add, let me know and I can get working on those.

### CODE REVIEW

**Comment by nicoleng12** [comment]
I am currently using your code in my branch and I think it's clear and meets the jira task. One thing: each of your case statements in SlimApp.jsx need a break statement

**Comment by gregquinn2001** [comment]
I'd say merge this as well (after fixing switch per @nicoleng12's comments

**Comment by nicoleng12** [comment]
I added breaks to the switch statements

**Comment by gregquinn2001** [comment]
merge away!

**Comment by nicoleng12** [comment]
Good to merge!

**Comment by gregquinn2001** [comment]
I'm going to merge this so I can just work from it. I tested patient mode and it still seems to work as well

**Pull request merged**
