### PR TITLE
Use placeholder

### PR DESCRIPTION
**Pull request by gregquinn2001**
changed the editor to use a placeholder (different text depending on patient or no-patient mode) instead of fixed text to start

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Looks good on the whole. As a general rule of thumb, let's try to use [strict equality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness) checks as we type up our code, otherwise Javascript will do it's earnest to come up with funky behavior.

**Comment by gregquinn2001** [comment]
I actually originally had === for that check but then it doesn't work. I always get else clause in both no patient and patient mode. Try it if you want. I changed it to == and it works. Any idea why?

**Comment by Dtphelan1** [comment]
Hm... odd. 
Something worth looking into. I think it's fine now if that's the case

**Comment by nicoleng12** [comment]
When I run it, I keep getting the if case for both patient mode and non patient mode...this is when using ==

I noticed that In other places in the code we also have null checks using double equals instead of triple.  Instead of I checking for null, we can always just check it it exists so instead of `if (this.props.patient == null)`  we can just do `if (!this.props.patient)`

**Comment by gregquinn2001** [comment]
wow that's strange! I'll try the exists check as you suggest @nicoleng12

**Comment by gregquinn2001** [comment]
this is strange. Now it's not working with any of the 3 cases!

**Comment by gregquinn2001** [comment]
when I rebased to master I lost passing in patient (thanks @nicoleng12!). I'll fix and commit

**Comment by gregquinn2001** [comment]
ok. all changed now to use the existence check (well non-existence check with the !)

**Comment by nicoleng12** [comment]
ok this looks good on my end now

**Comment by gregquinn2001** [comment]
I'll merge and create a JIRA to replace existence and == and === check with lodash equivalents? It will be in backlog at least that we have these in the code that should be changed. Make sense? Ok to merge @Dtphelan1 ?

**Comment by gregquinn2001** [comment]
wait, how does lodash help us with checking if a property exists or not?

**Comment by gregquinn2001** [comment]
would we use _.isUndefined to check for the existence of a property?

**Comment by nicoleng12** [comment]
Yes I think so. You can also check if null: https://lodash.com/docs/4.17.4#isNull

**Comment by gregquinn2001** [comment]
created jira. I'm merging

**Pull request merged**
