### PR TITLE
List visualizer

### PR DESCRIPTION
**Pull request by mtorchio**
Create a visualizer for lists of data. The Procedures section of the targeted data section now uses a new ListType that allows for a flexible number of columns of data. Also, each data item can be independently inserted using the plus buttons to the right of the data item. This also updates styling so that the leftmost column is either blue or salmon color depending on the presence of data, like the other columns.

Different rows containing different numbers of data elements (columns) are partially supported. If a data element is missing, set it to null.

Note: I noticed that the buttons in master aren't consistent. Some rows with missing data have plus buttons, others do not, and though the CSS seems to allow for black buttons, they are all grey. This pull request also fixes those.

Requires rebasing.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [X] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [**N/A**] Cheat sheet is updated
- [**N/A**] Demo script is updated 
- [**N/A**] Documentation on Wiki has been updated 
- [**N/A**] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [**N/A**] Note parser has been updated if structured phrases change

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [X] Existing tests passed
- [**N/A**] Added UI tests for slim mode 
- [**N/A**] Added UI tests for full mode - existing tests cover new functionality
- [**N/A**] Added backend tests for fluxNotes code
- [**N/A**] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] Looks like the font for missing items in tabular name value pair visualizer has changed with this pull request.

**Comment by gregquinn2001** [comment]
[GQ2] The key value tabular visualizer lines up the edge of its table with the horizontal lines. That is not the case for the List table where the horizontal lines end before the end of the table and the background color includes the + buttons for insertion. Can we make the tables align better style-wise? Please ask Dylan or Noranda for help if not clear how you'd do it immediately.

**Comment by jafeltra** [comment]
This looks good! The disabled buttons are visualized more consistently and the issuses Greg noticed are fixed. All the tests still pass and the existing tests seem to cover the new visualizer's capabilities.

[JA1] I noticed that there are some console.log's that we can probably remove. There also might be some old commented code in TabularListVisualizer that includes old console.log's that we might want to get rid of.

[JA2] How does this visualize missing data? I might have been trying to set missing data incorrectly, but I couldn't get it to display as missing.

**Comment by jafeltra** [comment]
JA2- After talking, the missing values should appear Salmon. The plus buttons should be disabled as well.

JA3- All cells should have a color since they are all present or missing.

**Comment by jafeltra** [comment]
The updates look good! JA1, JA2, and JA3 have all been addressed. Each cell has a color and a plus button and missing data is visualized with a salmon color and "Missing Data" in the cell with a disabled button.

Once this gets rebased, it looks good to me!

**Pull request merged**
