### PR TITLE
New allergies inserter

### PR DESCRIPTION
**Pull request by gregquinn2001**
JIRA 817.

Added some allergies to hard coded patient (on client side only right now). Implemented @allergies shortcut that inserts a summary of allergies for the patient. Just outputs names right now. Unfortunately, it looks like latest SHR model has changed substantially on web site vs. what our generated classes are.  As soon as ES6 classes have deserialization methods from SHR JSON and from FHIR, we can update which could be a lot of work.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [X] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [N/A ] Cheat sheet is updated
- [N/A ] Demo script is updated 
- [N/A ] Documentation on Wiki has been updated 
- [N/A ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [N/A ] Note parser has been updated if structured phrases change

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [X] Existing tests passed
- [N/A ] Added UI tests for slim mode 
- [N/A ] Added UI tests for full mode
- [N/A ] Added backend tests for fluxNotes code
- [N/A ] Added note parser examples to test new functionality

## Reviewer 1: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
Nice! All tests pass and it works in both chrome and in IE. Just one small thing:

[NN1] - All of the inserters we have insert right at the cursor. @allergies does too, but each of the following allergies is displayed on a new line. So it looks like this:

image

which looks a little strange.

Should the allergies be listed on the same line, separated by a comma or if we go with a list, should the insertion insert allergies on a new line instead of at the cursor? Just a thought.

**Comment by gregquinn2001** [comment]
I struggle with this one too. I modeled it after sample notes I've seen where it has an Allergies section and then the allergies are listed within that one per line. I wish we could support both somehow... Any ideas on the best way to handle this? A user can't insert a block of text and then make any changes within it (like adding new lines) so that's not an option right now.

**Comment by nicoleng12** [comment]
I'm not sure what the best way to handle it is. At first I was thinking of just inserting a new line before inserting the block of text, but like you mentioned, if the user makes a new line then inserts, there will be an extra blank line.

Should we leave it as is and expect the user to realize that they need to insert a new line before hitting the inserter? I feel that it is something they would learn quickly from using the inserter and seeing the behavior.

**Comment by gregquinn2001** [comment]
And it's something they can go back after the fact and do as well... not ideal but I'm not sure how else to handle it

**Comment by gregquinn2001** [comment]
Added JIRA 829 to support a conditional newline that inserters can use to cause a new line to be inserted if the current insertion point isn't already at the start of a new line. This could be used at the start this inserter's content to put the block of allergies on its own lines and not to start at the end of a current line in progress.

**Comment by nicoleng12** [comment]
Thanks for adding jira 829! Since NN1 will be covered in jira 829, I approve of the changes made in this branch

**Pull request merged**
