### PR TITLE
Implemented new context tray vertical list design

### PR DESCRIPTION
**Pull request by noranda**
# Implemented new context tray vertical list design

This pull request changes the design of the context tray, but not the functionality. Tabs are removed and replaced with a vertical list. When a context option is selected that triggers additional options, that option will be bolded and the additional options will appear in a section directly under the current section. Context options that do not trigger additional options (ex. `@patient`) will not render any additional sections and will not be bolded.

* Converted context tray tabs/buttons to a vertical list to match new UI design.
* Styled new vertical context options - note: options will bold when corresponding section displayed below.
* Added `icon-arrow-left` svg for context notes button to match design and added a hover transition.
* Moved inline styles to stylesheets.
* Whitespace deletions automatically performed by my editor.
* Fixed all tests and tested in IE.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter: Noranda

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- Cheat sheet is updated
- [x] Demo script is updated 
- Documentation on Wiki has been updated 
- Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- Added UI tests for slim mode 
- Added UI tests for full mode
- Added backend tests for fluxNotes code
- Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by noranda** [comment]
Rebased off master.

**Comment by gregquinn2001** [comment]
I like how compact this new format is. Nice job implementing it @noranda ! I think @laclark22 has a good question that we should consider. In addition, I see the following issues, but some of these may make more sense as new JIRA items to work after this pull request is merged:
[GQ1] When you switch to clinical notes, they are now cut off on the left side due to the width change
[GQ2] No way to get back from clinical notes to context tray still (definitely a separate JIRA)
[GQ3] When you insert a condition, no where is the name of that condition displayed (lobular carcinoma of breast). @condition is just bolded. I think we need a way to indicate the condition that the shortcuts shown in the next section apply to. Maybe the bolded name of the conditon should appear indented slightly under @condition. This could also help with GQ4 by allowing multiple indented condition names.
[GQ4] Can we handle multiple conditions right now without user confusion?
[GQ5] Are you filtering out empty contexts automatically from the UI? I use @procedure to insert a procedure and it isn't bolded and I don't get a section. That's fine (I like it actually) as long as if a shortcut is added that has @procedure as its parent, we would then see @procedure bolded with a new section below showing that new shortcut without requiring any coding changes to context tray UI.

**Comment by nicoleng12** [comment]
This looks really good Noranda!

I had the same comment as [GQ1]. Somewhat related to that styling, [NN1] it looks like you have made the width of the editor wider, which may be cutting into the notes area, thus cutting it off a bit? I'm viewing it in chrome at 100% zoom. It looks like the spacing between the icon and flux notes was reduced. Was that intentional?

Here is what it looked like in master:

image


Here is what the changes are:

image

**Comment by gregquinn2001** [comment]
@nicoleng12 I don't understand how NN1 is different than GQ1? Can you describe what additional issue is being identified by NN1 over GQ1 which identifies that the note icons in the clinical notes list are now getting cut off?

**Comment by noranda** [comment]
Thanks for all the great comments!

* [LC1] This is a good idea, but not something super easy to do. I suggest we make this a new JIRA task.
* [GQ1] This wasn't cutting off on my view but at smaller widths I now see that it does. I will fix this today.
* [GQ2] I'm confused by this. If you click on "Clinical notes", to get back to the context tray you can either click on an in progress note or click "New note". Can you clarify?
* [GQ3] Agreed this would be a good thing to add. Recommend making it a new JIRA task.
* [GQ4] Also a good idea. Perhaps we can lump this with the new GQ3 task?
* [GQ5] I am indeed filtering out empty contexts, otherwise it would render an empty section with a divider. If the context is not empty, then the term would get bolded and render the section below. You can see this with `@condition` by selecting "Fracture" which doesn't render a new section, and then selecting "Invasive ductal..." which does.
* [NN1] Are you talking about the Flux Notes logo spacing? This looks like an unintentional styling issue. I will fix this today.

**Comment by nicoleng12** [comment]
@noranda Yup! Thanks!

**Comment by gregquinn2001** [comment]
Please create jira issues for the ones you identify above. For GQ2, if you are in the middle of authoring a note and then click on the clinical notes link but then want the context tray back for the note you are authoring now, there's no obvious way to do it. I guess once we have the in-progress note showing up, you can click on that, but I'm not sure that's intuitive to users. It feels like we need a link to go back to the context tray without "loading" a note. This should definitely be a new JIRA though and perhaps should start with a discussion with Edwin.

**Comment by noranda** [comment]
Update:

* [LC1] [JIRA task](https://jira.mitre.org/browse/ASCODCP-841) created.
* [GQ1] Fixed. This involved a few steps:
     * Made notes section responsive to width of view
     * Doing so introduced issues in IE because IE is horrible at scaling SVGs
     * Converted SVGs to CSS, which had the bonus of automatically fixing the hover issue
* [GQ2] [JIRA task](https://jira.mitre.org/browse/ASCODCP-842) created.
* [GQ3] [JIRA task](https://jira.mitre.org/browse/ASCODCP-843) created.
* [GQ4] [JIRA task](https://jira.mitre.org/browse/ASCODCP-844) created.
* [GQ5] No change necessary.
* [NN1] Fixed.

**Comment by noranda** [comment]
Rebased off master.

**Comment by nicoleng12** [comment]
All issues have been addressed. All tests pass. This looks great!

**Comment by gregquinn2001** [comment]
I'm not thrilled with GQ3 and how it will demo, but let's show Edwin and have a discussion on how to improve on it. Thanks!

**Pull request merged**
