### PR TITLE
Adverse event buttons

### PR DESCRIPTION
**Pull request by laclark22**
Added the top 20 adverse events from the PATINA protocol as buttons and updated the app manager so they can be configured only for PATINA based trails.

## Submitter: Laura Clark

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- NA Cheat sheet is updated
- NA Demo script is updated 
- NA Documentation on Wiki has been updated 
- NA Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- NA Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] Added UI tests for slim mode 
- NA Added UI tests for full mode
- NA Added backend tests for fluxNotes code
- NA Added note parser examples to test new functionality

## Reviewer 1: Nicole

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
[DP1] Buttons on large screens look weird. @noranda Have you noticed this? 
boxes-layout

Second is not a concrete issue, but I'd like to open discussion on the current mechanism for getting the top 20 events. Looks like they've been moved to the top of the array of AE lookup, and we never make clear this explicit assumption that the top 20 events are the events we want buttons for. Could we make this a part of the customization? @gregquinn2001 Thoughts on this?

**Comment by nicoleng12** [comment]
Looks and and it works. Nice job!

I agree with @Dtphelan1 's comments about the mechanism for getting the top 20 events. Right now it's just getting the first 20 in the array? 

[NN1] - In slim mode, on the disease status form, the reference date should be hidden right? 

[NN2] - When I select an adverse event (via search field or clicking on one of the buttons), then decide to change it, I can only change it to one of the events that has a button. If I try to type in a different event, the search no longer works once a selection has been made.

I noticed in master I get an error in the console when I delete the adverse event from the search bar and then the search doesn't work anymore... Since this seems to be an error in master too, should we just make a jira for this?

**Comment by Dtphelan1** [comment]
Actually we have a JIRA issue that captures [NN2] -- ASCODCP-710:
"[Slim] On ToxicityForm, selecting an adverse event(AE) breaks AE auto-completion dropdown"

Does this wording read correctly? I meant for this issue to capture what youre describing, but if the wording isn't right feel free to edit it!

**Comment by nicoleng12** [comment]
@Dtphelan1  Yes that jira covers [NN2]

**Comment by Dtphelan1** [comment]
On that note, 710 seems to not be the case in Declarative-shortcuts branch, so Greg might have resolved it. Maybe we shouldn't put too much effort into that fix.

**Comment by gregquinn2001** [comment]
Cool. Didn't mean to fix it! :)

**Comment by jafeltra** [comment]
This looks good!

[JA1] This is small, but I think that the Adverse Event buttons should have rounded corners to match the style of "Choose one"-type buttons (spaced apart and rounded corners - see Disease Status buttons as an example).

**Comment by jafeltra** [comment]
I just pushed a commit that I think handles some of the styling that DP1 was referring to and fixes JA1. If @noranda, @laclark22, or @Dtphelan1 have opinions on how to improve the potential fix for DP1, let me know!

**Comment by gregquinn2001** [comment]
Unfortunately, @laclark22 we will need to rebase again in this branch since declarative shortcut major change went into master. Let's work through it together in those 10 minutes you have free tomorrow!

**Comment by danlee1025** [comment]
I just tested out a rebase locally and it isn't too bad, but I'll let you guys work it out in case I miss anything.

**Comment by gregquinn2001** [comment]
It looks like only 1 file has conflicts (the obvious file to have them of course) so it may not be too bad, but if you already have it done we should leverage that. Were the conflicts easy to resolve or do you need help from Laura to make sure?

**Comment by danlee1025** [comment]
Looks like easy fixes, I will push up the rebase after the problem below is addressed.

I'm running into some UI test failures though(also happening on master).  Greg, can you run the UI tests on master to make sure it's not only happening on my machine?  The date selector is not showing up in the context panel for clinical trial enrollment and disease status as of date.

**Comment by gregquinn2001** [comment]
running now.

**Comment by gregquinn2001** [comment]
wow 12 failed

**Comment by danlee1025** [comment]
12? on master? I only got 2... Hmm

**Comment by gregquinn2001** [comment]
yeah master

**Comment by gregquinn2001** [comment]
Ok. I had to kill yarn start and restart it and then I got 2. I fixed the problem in master. All tests pass and the #date shortcut shows up again in the context when it should in patient mode. Great catch Dan!

**Comment by danlee1025** [comment]
Ok thanks Greg... I rebased the branch.

**Comment by laclark22** [comment]
Updated so that add manager now holds the top 20 adverse events.

**Comment by laclark22** [comment]
Addressed lint error and changed reference date back to false in app manager

**Comment by nicoleng12** [comment]
All issues have been addressed. All tests pass. Nice job Laura!

**Pull request merged**
