### PR TITLE
Differentiated the buttons in Slim Mode progression so that button ty…

### PR DESCRIPTION
**Pull request by mtorchio**
…pes are clear. Status is a single selection so buttons are separated and have a border. Reason is a multi-select so buttons appear next to each other.

### CODE REVIEW

**Comment by gregquinn2001** [comment]
did the mockup use the round cornered buttons vs rectangular ones as well?

Also, can we make the first button always align on the left side regardless of which type they are?

**Comment by mtorchio** [comment]
Yes, the mockup used rounded buttons on top. I'm looking into the best way to align buttons to the left side.

**Comment by gregquinn2001** [comment]
Maybe something like: https://css-tricks.com/snippets/css/remove-margins-first-element/

**Comment by mtorchio** [comment]
We were setting the margins in code in the JSX style attribute, so I just made the change there. I tried what Greg's link recommended but couldn't get pseudo-selectors to move the buttons over.

**Comment by mtorchio** [comment]
Thanks! I'm going to rebase and then merge this in.

**Pull request merged**
