### PR TITLE
Forms with descriptive text

### PR DESCRIPTION
**Pull request by Dtphelan1**
Addresses JIRA 412: Add descriptive text to back-end and display in UI. 

Added getDescription functions to each of the lookup objects exported from the lib folder. getDescription takes a structuredField and gets the description to go along with that structuredField .

### CODE REVIEW

**Comment by gregquinn2001** [comment]
toxicity is crashing resulting in not getting anything but #toxicity in copy button

Uncaught TypeError: Cannot read property 'adverseEvent' of null
    at Object.ToxicityForm._this.handleUpdateAdverseEventInput [as onUpdateInput] (ToxicityForm.jsx:149)
    at AutoComplete.<anonymous> (AutoComplete.js:225)
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactUpdatesFlushTransaction.close (ReactUpdates.js:59)
    at ReactUpdatesFlushTransaction.closeAll (Transaction.js:206)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:153)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:89)
    at Object.flushBatchedUpdates (ReactUpdates.js:172)
    at ReactDefaultBatchingStrategyTransaction.closeAll (Transaction.js:206)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:153)

**Comment by gregquinn2001** [comment]
happens on master branch as well actually

**Comment by gregquinn2001** [comment]
I'll log a jira for it

**Comment by gregquinn2001** [comment]
There's no descriptive text for each reason on progression form?

**Comment by nicoleng12** [comment]
I also see the error that Greg is getting. The copy button for toxicity is not getting updated with the shortcut string

I noticed in the mockups that there are descriptions for the adverse events too. 
image

The code does not currently have that. Right now the adverse event just displays the name of the adverse event without the description. 
image

**Comment by gregquinn2001** [comment]
Disease progression description at top of progression form has a typo in 2nd sentence: "It is the point of care which includes objective measures like tumor growth,"

**Comment by gregquinn2001** [comment]
Add it to the JIRA issue. It is not a problem with this pull request

**Comment by gregquinn2001** [comment]
In the description of toxicity at the top, should we incorporate some basic text indicating that we are using the CTCAE version x and spell out CTCAE?

Common Terminology Criteria for Adverse Events (CTCAE) version 4.03 (June 14, 2010)

**Comment by Dtphelan1** [comment]
a. Didn't notice the descriptions for AE and Grade's in the mockups -- I can work on adding that before merging. 
b. Good catch on the toxicity problem. 
c. I'm on board with the text regarding the current version!

**Comment by gregquinn2001** [comment]
What about progression status and reasons. each has a description in progression_lookup but they aren't displayed currently? Is that based on the mock-ups not showing anything?

**Comment by Dtphelan1** [comment]
Thanks for adding the ID's. And yeah -- they weren't shown in the mock ups so I didn't prioritize them. Since those will likely be buttons/checkboxes, maybe we can add tooltips if we want? Up to you whether or not we add that to this PR though.

**Comment by gregquinn2001** [comment]
So for GQ1, I looked back at concept and agree that tooltips may make the most sense like Nicole did for staging.

**Comment by Dtphelan1** [comment]
So we've addressed GQ2 and GQ3 with these new commits. 

For GQ1, since those changes are intertwined with the progression form redesign, we will add this issue to the existing JIRA item's description and address it then. 

Re: Nicole's suggestion for the adverseEvent descriptions, we will be able to successfully include descriptions of adverseEvents when we remove support for multiple toxicities. So we will put that off for now.

**Comment by nicoleng12** [comment]
The changes look good. Since GQ1 will be done as part of another jira issue (after completing issue 425), I think this is good to merge

**Pull request merged**
