### PR TITLE
Tabular viz new inserter

### PR DESCRIPTION
**Pull request by Dtphelan1**
Addresses ASCODCP-885: Integrate new insertion methodology into Tabular visualizer

Removes pluses from the tabular visualizer with the new insertion methodology. Based on conversations with @gregquinn2001  and @edwinychoi we've replaced the hover menu-trigger with a click menu-trigger. This change is made in both this new instance of the inserter and the original instance. 

Known issues: 
- A change made in my previous PR disabled scrolling on home page for flux notes. @noranda discussed a way to revert this with me and pushed that change out to master as discussed; sadly this makes the application buggy to use in IE, bringing back the issue I was trying to fix in my previous PR. I spent considerable time trying to find a combination of overflow definitions in CSS files that would remedy this bug and had no luck. I present the feature as-is for feedback and criticism. 
- No UI tests were made for reasons discussed in my previous PR.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- **N/A** Cheat sheet is updated
- **N/A** Demo script is updated 
- **N/A** Documentation on Wiki has been updated 
- **N/A** Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- **N/A** Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- **N/A** Added UI tests for slim mode 
- **N/A** Added UI tests for full mode
- **N/A** Added backend tests for fluxNotes code
- **N/A** Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
[GQ1] I'm going to remove the offsets we used when hovering was the trigger. Let me know what you think of that. 
[GQ2] Looking into this now! Very weird...

**Comment by Dtphelan1** [comment]
After discussions at standup we are going to make a separate JIRA for GQ2 since this is blocking other tasks. 
GQ1 has been resolved and approved with @gregquinn2001 in person.

**Comment by mtorchio** [comment]
This looks so much better than the plus signs!

[MT1] There is a console warning when clicking a new underlined item: Warning: Unknown props `anchorReference`, `anchorPosition`, `onClose` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Modal)

I am still seeing GQ1 - the "Insert" popup is always in the same location, far left of the screen halfway down.

**Comment by mtorchio** [comment]
Running yarn install fixed those issues. I'm running the tests now.

**Pull request merged**
