### PR TITLE
Rest client

### PR DESCRIPTION
**Pull request by jafeltra**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

This pull request uses the REST API to return the hardcoded patient JSON. A separate route, /p2, uses the REST API. Some things to note about this PR:
- 3 separate repositories were created on standardhealth:
  - shr-rest-api (https://github.com/standardhealth/shr-rest-api) holds the yaml and json files that define the REST API. Either of these files can be changed to change the API, but both should be updated to match.
  - shr-node-server (https://github.com/standardhealth/shr-node-server) is the node implementation of the REST API. This was generated from the Swagger.yaml file in the shr-rest-api repo.
  - shr-javascript-client (https://github.com/standardhealth/shr-javascript-client) is the javascript client implementation of the REST API. This was generated from the Swagger.yaml file in the shr-rest-api repo.
  - Each repo has a README that explains how to use it and how to update the generated code. Any feedback on these repos is appreciated. I've pushed all changes I made after setting up the repositories directly to master.
- Flux Notes does not yet handle getting data asynchronously, so the library inside shr-javascript-client was modified to use a synchronous call. Flux now uses the javascript client library to make the call, and that library makes a synchronous call to the node implementation of the rest api.
- Due to the change we made in the shr-javascript-client library, it cannot run in the NodeJS environment, but it can run in a browser. This means it works correctly if you navigate to /p2, but the test for getting a patient will fail. The test was commented out for now because we eventually want to be able to use an asynchronous call, which would remove the workaround and allow the test the pass.
- I updated the Technologies Used on the Wiki to include the shr_rest_client module we now use. I can create a separate page that gives an outline on how to run all the pieces together if that seems useful.

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] I haven't done this but it should be fine. Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [x] N/A Cheat sheet is updated
- [x] N/A Demo script is updated 
- [x] Documentation on Wiki has been updated 
- [x] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] N/A Added UI tests for slim mode 
- [x] N/A Added UI tests for full mode
- [x] Added backend tests for fluxNotes code
- [x] N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Mike T

- [X] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [X] The tests appropriately test the new code, including edge cases
- [X] You have tried to break the code

### CODE REVIEW

**Comment by mtorchio** [comment]
The code looks really good! I agree that we should capture the async change in JIRA. I'm running it now...

**Comment by jafeltra** [comment]
Thanks for the reviews all! I did create 2 JIRA tasks for remaining items:
- ASCODCP-721: Getting the swagger-codegen tool to run so we can use that instead of the online editor
- ASCODCP-722: Getting the Flux App to run when loading data asynchronously, which also involves removing the manual changes made to the javascript-client files and uncommenting the test.

**Comment by nicoleng12** [comment]
Everything looks good to me! The code is clean and well documented. It runs and uses the server to provide the data for patient mode.

**Comment by jafeltra** [comment]
Thanks all! I'm going to merge this in now.

**Pull request merged**
