### PR TITLE
Remove targeted data control

### PR DESCRIPTION
**Pull request by nicoleng12**
This PR covers jira issues: 772, 776, and 757.

772
- Removed Targeted Data Control component
- Moved condition selection and event selection into the patient control panel
- Re styled the patient control panel so that all of the UI pieces fit nicely and look ok on a smaller screen

776
- @mtorchio Reduced spacing between icons and text for Flux notes icon and patient photo

757
- Edited text in search box

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- N/A Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] minor nit but the patient's name doesn't line up (on left side) with the smaller data attributes below it. It doesn't look right to me. I'm in Chrome on Windows at 100% zoom.
[GQ2] Should the logged in user name appear left justified aligned with the icon rather than the words "Flux Notes"? I think it might look better?

**Comment by gregquinn2001** [comment]
Very cool though! I think it looks and works so much better now!

**Comment by nicoleng12** [comment]
Thanks for the feedback @gregquinn2001 ! I've addressed GQ1 and GQ2

**Comment by jafeltra** [comment]
This looks good! One thing I noticed:

[JA1] There seems to be extra whitespace on the bottom of the app that wasn't there before. Maybe a height calculation needs to be adjusted?

**Comment by gregquinn2001** [comment]
Good catch on JA1. I definitely see that now!

**Comment by jafeltra** [comment]
[JA2?] The "View" icon button seem closer to each other than they are in master. Was that part of the intentional changes?

**Comment by gregquinn2001** [comment]
For JA2, I think it looks good though. Do you think it looked better the way it was in master?

**Comment by nicoleng12** [comment]
Good catch @jafeltra . I prefer it with the spacing like it was in master. The spacing must have gotten lost with some of the new styling. I added spacing so that the view buttons are separated from each other. JA2 has been addressed

**Comment by jafeltra** [comment]
I worked with Dylan and fixed the height of the panel that was causing the extra white space at the bottom of the page, so JA1 is fixed now.

All the tests pass and everything else looks good to me!

**Pull request merged**
