### PR TITLE
Implement view note

### PR DESCRIPTION
**Pull request by nicoleng12**
In post-encounter mode:
- Switching to clinical notes view and clicking an existing note loads the note into the editor in readonly mode. Users cannot enter text into the editor since this is readonly. The note assistant stays in clinical notes view
- Switching to clinical notes view and clicking add new note, then clicking back to clinical notes view and clicking on the newly added in-progress note loads the note into the editor in edit mode. Users can type and edit the note since the note is in-progress and is not yet signed. The note assistant switches to the context tray

In pre-encounter mode;
- Switching to pre-encounter mode and clicking on an existing note adds the editor to the layout and inserts the content of the selected note in read only mode
- Switching to pre-encounter mode, clicking on add new note, switching to clinical notes view, and selecting the in progress note loads the note into the editor in edit mode

Added UI tests to test the above cases

This PR does not look at saving notes. That is covered in another jira task

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- [x] Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Noranda

- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by noranda** [comment]
Good work! Just a few issues I can see:

[NB1] - When you click on an existing note and the note displays in read-only, clicking on targeted data section add [+] buttons will still add terms even though it's read-only. My guess is that we don't want this, so perhaps all the [+] buttons should be grayed out to show they are disabled?

[NB2] - When clicking on a new note, entering `@gender`, clicking back to clinical notes, and then clicking on "In progress note", the note is edited to include `@patient`. Is this by design?

[NB3] - After completing the steps in NB2, adding another context (ex. `@age`), clicking back to clinical notes, and then clicking again on "In progress note" deletes the new context we added. Is this because we are not yet saving notes?

**Comment by nicoleng12** [comment]
Thanks @noranda for reviewing! 

NB1 has been addressed. I added a check so that clicking on the plus button no longer inserts if in read only mode. Changing the color of the button and disabling the button is less straightforward and is covered by jira 788 (https://jira.mitre.org/browse/ASCODCP-788).  Let me know if the current fix I have is good enough for now for this PR.

NB2 is expected because we don't currently have functionality to save notes. Currently in-progress notes are hard coded. That's why clicking on it overwrites what you have entered with some hard coded info.

NB3 is also expected because of the same reason provided for NB2.

**Comment by nicoleng12** [comment]
Rebased on master

**Comment by noranda** [comment]
Looks good!

**Comment by gregquinn2001** [comment]
I'm going to review this now

**Comment by gregquinn2001** [comment]
[GQ1] Any chance we can pull the note header values from the existing note when we display it?

**Comment by gregquinn2001** [comment]
Thank you for logging jira 823. Loading an existing note should never change the summary! We may want to change some of the existing notes by removing hash tags to align them with our structured data and provide test cases for our future data curation functionality!

**Comment by nicoleng12** [comment]
@gregquinn2001  for GQ1, I'm pulling all of the information for the note from the hardcodedpatient.json. So if you update notes in the json, it should be reflected in the app. Is that what you meant?

**Comment by nicoleng12** [comment]
@gregquinn2001 I'll look into [GQ1]. You mean when we click on existing note, display some of that info in the note?

**Comment by nicoleng12** [comment]
@gregquinn2001 GQ1 has been addressed

**Comment by nicoleng12** [comment]
After talking with @gregquinn2001 I misunderstood the question. The latest push i have the metadata in the note itself. I am currently looking into updating the info in the note header (above the editor area)

**Comment by nicoleng12** [comment]
Spoke with @gregquinn2001. Undid latest commit and making a separate jira issue.

**Comment by gregquinn2001** [comment]
[GQ2] Toolbar still active. When editor in read only mode can we either remove or disable toolbar?

**Comment by nicoleng12** [comment]
After talking with @gregquinn2001 made a jira issue for GQ1. GQ2 has been addressed. In read only mode, user cannot click on the toolbar buttons and the cursor changes to an arrow to indicate that the buttons are not clickable

**Pull request merged**
