### PR TITLE
Banded regions in line chart

### PR DESCRIPTION
**Pull request by nicoleng12**
Banded regions added to line chart for white blood cell lab results

- Updated white blood count cell values in HardCodedPatient.json so that values cross all three bands in the line graph 
- Used referenceArea in recharts lib to create the bands
- line chart adds bands if the bands attribute is provided in summary meta data, otherwise the the chart is drawn without bands

Known issues/things to look into:
- Values for the white blood cell count need to be verified by a clinician for what the values should be for a typical breast cancer patient
- Band range values (low and high) need to be verified by a clinician. Current band ranges used are based on a quick google search for normal white blood cell values 

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- N/A Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
@danlee1025 pointed out that the way I had set up the code, it was limited to just 3 bands. He and I talked and he proposed some fixes that allows for any number of bands as well as the case where bands might have the same color (in the mockups, cholesterol has 2 "bad" regions that are red that surround a middle good region). I have incorporated Dan's edits which make the bands more versatile for any type of lab data we might have to plot

**Comment by gregquinn2001** [comment]
Thanks @danlee1025 ! @nicoleng12 this looks really good to me!

**Comment by gregquinn2001** [comment]
[GQ1] Why do we need assessment and color as attributes of a band? The assessment should be the only thing provided in the metadata and the visualizer should map that to a color. The metadata should be data that drives visualization and not visualization properties directly if that makes sense.

**Comment by danlee1025** [comment]
For GQ1, Nicole and I discussed it a little bit.  I had added color attribute just for testing but Nicole thought it would be good to leave it in for more versatility in case we wanted different colors in the future.  We can definitely remove the color property if you don't think it belongs in the metadata.

**Comment by jafeltra** [comment]
This looks really good! I have one question that we talked a little about in person, but wanted to also pose to others. Would we want to have a band for the remaining uncolored top portion of the y axis? This might mean that the top band would be another color. It initially seemed odd to me that part of the graph was just white without a band, but I also understand that stopping the green band at 10 and not extending it to the full height of the graph is the best choice since a value above 10 might not be considered "good" anymore. Would we want to have a fourth band that goes from 10 to the max height of the graph? I know Nicole had said this might be difficult with the Recharts library, so this could be a separate Jira, if we want it at all.

[JA1] Can we combine the if else statement that renders the LineChart so that we only have it once and just have the renderedBands return null if the graph doesn't have any bands? I think this would help consolidate some of the code.

**Comment by nicoleng12** [comment]
Great suggestions everyone! For [GQ1] I moved the colors out of summary meta data and put the case statements back into the banded line chart visualizer. @gregquinn2001  I agree that we should keep chart styling withing the chart component. @danlee1025 We can still add additional colors if there are more bands or if some charts need different colors. We can handle this from inside the chart component. 

For [JA1] I followed Julia's suggestions which cleaned up the code nicely. Thanks!

**Comment by jafeltra** [comment]
This looks good to me! After talking, we decided to hold off on filling in the top region of the chart until we find out if it is necessary. If it is, we will add a Jira to the backlog. All the tests pass and JA1 is addressed. Nice job!

**Comment by jafeltra** [comment]
Once this is rebased, I can merge it.

**Comment by nicoleng12** [comment]
Thanks! I just rebased

**Pull request merged**
