### PR TITLE
staging updates between 3 places now (jira 357)

### PR DESCRIPTION
**Pull request by gregquinn2001**
changing staging in form updates dropdowns in current structured field. Also updates patient summary like it did in old app. added jira to address context (e.g., condition) and create a new staging per shortcut

### CODE REVIEW

**Comment by Dtphelan1** [comment]
On an irregular basis, I get a failure to sync that results in the following console error: 
At Patient.jsx:544, Uncaught TypeError: Cannot read property 'entryType' of undefined.

**Comment by Dtphelan1** [comment]
It appears that certain combinations of TNM values don't work. Maybe this is intentional behavior?

**Comment by gregquinn2001** [comment]
Any thoughts on how to reproduce? Could you post the entire stack trace?

**Comment by gregquinn2001** [comment]
Yes, those combinations are invalid and show as undefined on the bottom of the right form. Should be very similar behavior to what we had before.

**Comment by Dtphelan1** [comment]
Full description of bug: On the initial definition of Staging values, if an invalid selection of values is chosen, the link to the shortcut object stops functioning. Console continues to log an error in Patient.jsx:544.

**Comment by gregquinn2001** [comment]
I fixed a few cases involving Tis and N1mi that weren't working correctly but no exceptions still

**Comment by gregquinn2001** [comment]
let me see if I can reproduce that. thanks!

**Comment by gregquinn2001** [comment]
awesome. reproduced it. thanks!

**Comment by Dtphelan1** [comment]
Okay so I 've got the problem nearly pinned down. It has to do with the lack of a null check when you go to insert a staging value after lookup. The null value gets generated in StagingShortcut in updatePatient; the null value doesn't get checked in the call to patient.addObservationToCondition, which is definied in Patient.jsx:736

**Comment by gregquinn2001** [comment]
I know how to fix it. I'm just on a call right now. I'll fix it after scrum probably

**Comment by Dtphelan1** [comment]
Sounds good!

**Comment by nicoleng12** [comment]
The summary panel, shortcut, and right form panel all sync nicely for staging. I see the bug that Dylan mentioned and it seems like you guys have a fix for it so that should be good. I'm sure you guys already know some of the invalid entries but in case Mike looks at this, an example invalid staging entry you can use to reproduce the bug is T2, N1mi, M0

**Comment by gregquinn2001** [comment]
ok meetings finally ended at 12 so I was able to fix the problem and commit. let me know if you're ok with me merging before burndown

**Comment by nicoleng12** [comment]
Tested and the bug seems to be fixed. Looks good on my end

**Comment by Dtphelan1** [comment]
Bug has been fixed and warnings have been supressed, looks good to me!

**Pull request merged**
