### PR TITLE
created a post encounter visit reason referencing previous visit

### PR DESCRIPTION
**Pull request by laclark22**
Created a new section in summary metadata with a visit reason for post encounter mode. This reason references the last appointment in the hard coded patient closes to the current time. I also updated hard coded patient so that the previous encounter and the next encounter are the same. This will make sure that the demo will not be affected. 

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- NA Cheat sheet is updated
- NA Demo script is updated 
- NA Documentation on Wiki has been updated 
- NA Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- NA Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- NA Added UI tests for slim mode 
- NA Added UI tests for full mode
- NA Added backend tests for fluxNotes code
- NA Added note parser examples to test new functionality

## Reviewer 1: Mike

- [X] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [X] The tests appropriately test the new code, including edge cases
- [X] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Looks good. One change I'd recommend:
[GQ1] let's instantiate the moment that we use in isAfter or isBefore outside the loop in a variable like const now = new moment() and then use now as the argument to isAfter and isBefore.

[GQ2] if there are multiple previous encounters, I'm not sure the getPreviousEncounterReason will return the reason from the right one. getEncountersChronologically sorts them from oldest to newest. You then filter out any after the date and take the first one. I think you want to take the last one in the list as it would be most recent, right?

**Comment by laclark22** [comment]
Addressed GQ1 and GQ2. Also updated hard coded patient so that the visit reason is in past tense for in post encounter mode.

**Comment by mtorchio** [comment]
The code looks good, getPreviousEncounter and getNextEncounter look similar which is a good thing. Chrome tests and backend tests pass. I tested it by adding another past appointment to the hard coded patient and this code correctly displays the most recent appointment in the past in Post Encounter, and the soonest appointment in the future in Pre Encounter. The @reason for previous visit shortcut isn't in place yet so inserting the reason results in "@reason for previous visit[[Feb13Debra Hernandez672 is coming in to see Dr. X123 Y987 for a check up on the progress of her treatment for Invasive ductal carcinoma of the breast]]" in the editor.

**Comment by laclark22** [comment]
Addressed Mike's comment.

**Pull request merged**
