### PR TITLE
Suggestion to insert now aligned with dropdown and text on page

### PR DESCRIPTION
**Pull request by Dtphelan1**
Item to be inserted on enter wasn't aligned well with dropdown and/or currently selected item in many cases. These changes should address that. 

To test: Try multiple permutations on the shortcut dropdowns and make sure the expected element is the one inserted. 

Additionally, the files in the slate-suggestion dir have been updated to use their pre-compiled ES6 src files, not the ES5 compiled files provided by NPM. This means that the files in flux\src\lib\slate-suggestions-dist should be identical with the files in [my fork](https://github.com/Dtphelan1/slate-suggestions/tree/fixed-one-off-isses/lib) of slate-suggestions. These will be the files I use to make a PR on [oozou/slate-suggestions](https://github.com/oozou/slate-suggestions).

Let me know if there is anything you see. If there are no stopping bugs,  I'd love to have this PR pushed through before 1:00 in time for a demo.

### CODE REVIEW

**Comment by nicoleng12** [comment]
Tested this with drop downs for condition, staging, progression, and toxicity, Pressing enter correctly selects the item from the drop down. This looks good on my end

**Comment by gregquinn2001** [comment]
When you choose from autoselect now, I don't get focus in the editor. When I insert via right panel or via typing, I maintain focus in editor. We can just log this as a jira and still merge this though if you want

**Comment by gregquinn2001** [comment]
I'll add the jira. I assume Dylan is preparing for the demo

**Comment by Dtphelan1** [comment]
I think we should merge it in and log the jira issue. For the record, I was also having issues shifting focus to the editor on master prior to the merge.

**Comment by Dtphelan1** [comment]
Thanks Greg!

**Comment by nicoleng12** [comment]
I already made the jira. feel free to add comments (issue 489)

**Comment by gregquinn2001** [comment]
deleted mine as we did them at same time

**Pull request merged**
