### PR TITLE
Saving notes

### PR DESCRIPTION
**Pull request by mtorchio**
This pull request adds the saving of notes to the in-memory PatientRecord. Notes are saved whenever the Slate editor is updated, including text and structured fields. The New Note button creates a new in-progress note which is automatically saved. When the editor is first loaded, it is not associated with a note. When you begin to type in the editor, a new note is created and saved. Several bugs related to empty notes and saving when switching to view another note were uncovered and resolved.

Please review and try to break this by finding a way to lose data. 

This will have to be rebased.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [X] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [N/A] Cheat sheet is updated
- [N/A] Demo script is updated 
- [N/A] Documentation on Wiki has been updated 
- [N/A] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [N/A] Note parser has been updated if structured phrases change

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [X] Existing tests passed
- [N/A] Added UI tests for slim mode 
- [X] Added UI tests for full mode
- [N/A] Added backend tests for fluxNotes code
- [N/A] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Very cool to be able to switch between existing and in progress notes and have it behave correctly!

[GQ1] onChange in FluxNotesEditor builds a selection to use to pull current content. That code assumes the cursor is at the end of the note. If you arrow back in the note and then insert some new content and then switch notes and come back, all the content after the cursor is lost.

**Comment by gregquinn2001** [comment]
[GQ2] Variable in onChange in FluxNotesEditor shouldn't be called allTextSelected. It should be called entireNote or allText or something that says it will contain the entire contents of the note regardless of selection. Ideally we'd save the current selection location as well, but we can create a JIRA for that to consider in the future.

**Comment by jafeltra** [comment]
This looks really good! It's cool to actually be able to reopen notes. I can reproduce GQ1. I found a few other small things, but I can help look into them tomorrow morning!

[JA1] If you only click on a shortcut in the context tray and then go back to the list of notes, that note you just created with one shortcut isn't displayed. However, once you click the new note button and go back to the list of notes, it is there and has the one shortcut in it.
[JA2] Two of the UI tests are failing for me. ('Clicking on an in-progress note in post encounter mode loads the note in the editor' and 'Clicking New Note button adds a new in progress note to the list'). I think the first one is actually failing due to something similar to JA1.

It also looks like there is some old commented code in ClinicalEventSelection.jsx that I'm not sure if we still want.

**Comment by mtorchio** [comment]
Addressed GQ1, GQ2, JA1, JA2, and removed the commented-out code Julia mentioned

**Comment by jafeltra** [comment]
This looks good! All the above issues are addressed. All the tests pass now.

**Comment by gregquinn2001** [comment]
rebased and all tests still pass

**Pull request merged**
