### PR TITLE
Added flux notes logos and inserted the color logo into the page header

### PR DESCRIPTION
**Pull request by mtorchio**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [ ] 4-space indents - convert any tabs to spaces
- [ ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added UI tests for slim mode 
- [ ] Added UI tests for full mode
- [ ] Added backend tests for fluxNotes code
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
bump. Any word on a fix @mtorchio

**Comment by Dtphelan1** [comment]
Yeah it looks like Edwin didn't include an inverted color logo. We should ask for one, but we shouldn't worry about using it now because his newest mockups use the color that @mtorchio is using now, just with a white navbar. So I'm fine merging so long as we follow up with Edwin in case we need this long term

**Comment by jafeltra** [comment]
I agree with Dylan.

**Comment by gregquinn2001** [comment]
ok. sounds like you are both on top of this and @Dtphelan1  fixed the issue he reported. Do we need to create a jira to restyle navbar per latest concepts or do we align now?

**Comment by Dtphelan1** [comment]
We can just align now.

**Comment by gregquinn2001** [comment]
I was asking if we already did align. if we don't, we should not merge this until we do as the task was to incorporate the logo per the concept, right?

**Comment by gregquinn2001** [comment]
If it's going to be a heavy lift, then we should discuss further and decide to just get the logo in there and create a jira to update it to align later. If we are doing it now, @Dtphelan1 can you do it or @mtorchio  should wait until after the patient test cases for the deserialize branch are done please!

**Comment by Dtphelan1** [comment]
I'm working on it now, it won't be a heavy life -- just changing font colors too.

**Comment by gregquinn2001** [comment]
Thanks @Dtphelan1 !

**Comment by jafeltra** [comment]
This looks good! I just pushed a commit after talking to Dylan that removes warnings that were created by the color prop that was added.

**Pull request merged**
