### PR TITLE
Changed Timeline to use asOfDate

### PR DESCRIPTION
**Pull request by danlee1025**
Only a couple lines changed(if you do a git diff -w), but I refactored this function to follow the style guide.

### CODE REVIEW

**Comment by jafeltra** [comment]
The changes look good to me! The icon and hover text use the as of date now. I didn't notice the warnings that Mike saw. I like the idea of pointing out the updates to the timeline in the demo script. I also agree that it would be useful to start adding a few tests around new features so we can start to keep up with the changes we make.

**Comment by gregquinn2001** [comment]
@Dtphelan1 could we do a UI test that would create a new progression by entering #disease status #stable ... into the editor and then verifying that the summary and timeline are updated appropriately?

**Comment by gregquinn2001** [comment]
I already logged bug ASCODCP-596 (https://jira.mitre.org/secure/RapidBoard.jspa?rapidView=553&projectKey=ASCODCP&view=planning&selectedIssue=ASCODCP-596) because I don't think the summary is updating correctly so it would be ok if that part of the test was left to that bug or if it just failed for now...

**Comment by Dtphelan1** [comment]
Yeah @gregquinn2001 that's exactly what I was thinking. @daniellee1025  want to put something together that meets those testing requirements? For information about the different types of testing libraries we use look [here](https://github.com/standardhealth/flux/wiki/Flux-Capture-Prototype-%28Flux-Notes%29#technologies-used) (you'll probably want to look into the testcafe library). And for examples of the testing, you can check the test/ui/ directory in the project. Let me know if you need any help with this!

**Comment by danlee1025** [comment]
@Dtphelan1 I will look into and ask you for help if needed.  I'm mostly working on my other project today so I probably won't get to it until Monday.

**Comment by gregquinn2001** [comment]
The test fails when I run it "Typing a progression note with as of date in the editor results in a new progression item on the timeline"

**Comment by danlee1025** [comment]
@gregquinn2001 I'll have the fixed test pushed up soon.  I was pushing up the inital test to work with Dylan.

**Comment by gregquinn2001** [comment]
Sorry Dan!

**Comment by nicoleng12** [comment]
This looks good Dan. The timeline is using as of dates and when I add a disease status with an as of date, it gets added to the timeline. I think once the tests are added and they work/pass, this branch should be good to merge with master

**Comment by danlee1025** [comment]
@gregquinn2001 @nicoleng12 I pushed the UI test up now and all the tests pass on my end.  Can you guys take another look?

**Comment by danlee1025** [comment]
Should remain consistent if patient data does not change.  I tried looping through the progression items and checking if any of the progression items contained today's date and setting a boolean to true and then asserting after the for loop.

I could not get this condition `if(hoverTextItemDate.innerText === today.toString())` to work, but the assert equality works.  Any ideas?

**Comment by jafeltra** [comment]
One thing that I ran into when trying to use the `.innerText`, is that it seems to be asynchronous. If you add `await` before getting the `.innerText` it might help. Something like: `const text = await hoverTextItemDate.innerText` and using that `text` variable in the comparison. Maybe that would help here too?

**Comment by nicoleng12** [comment]
Julia and I worked on some of the unit tests together and I just want to second her comment. Adding an await should help you set your variable because it's asynchronous. I had to do that in my unit tests as well.

Also, all your tests pass. I can approve this and merge but @danlee1025 are you trying Julia's suggestions first? If you are, I can hold off

**Comment by danlee1025** [comment]
@nicoleng12 I would like to try out Julia's suggestion, will be pretty quick.

**Comment by danlee1025** [comment]
@jafeltra @nicoleng12 Thanks for the help, that worked.  I had an await when selecting the element so didn't even think to put an await when selecting the innertext.  It should be good to go now.

**Comment by nicoleng12** [comment]
All the tests pass. Nice job Dan! I'm merging this

**Pull request merged**
