### PR TITLE
Move clinical notes tab

### PR DESCRIPTION
**Pull request by nicoleng12**
Moved clinical notes tab from left panel into the Notes Panel. Created a new component in Notes Panel called Note Assistant which contains the context tray and the list of existing clinical notes. This branch does not cover styling of the notes (preview view). That is covered in a different jira task. 

Users can click on the arrow in the Note Assistant to switch from viewing the context tray to viewing the list of clinical notes. The clinical notes view has a button go back to editing the current note (functionality of button has not been implemented as it's not part of this task and is part of a different task). 

Pre encounter view includes NotesPanel with the editor view disabled as well as the context tray. Only the list of clinical notes is displayed.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated (current demo script doesn't go over viewing existing notes)
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- [x] Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by mtorchio** [comment]
This looks great!

**Comment by danlee1025** [comment]
Everything looks great!

Can we remove the renderedNotes function from DataSummaryPanel.jsx, I don't think it is being called anymore.  I think it may have gotten back in there when the branch was rebased.

**Comment by mtorchio** [comment]
I will wait to approve until we answer Dan's question above (DL1?).

**Comment by nicoleng12** [comment]
Great catch @danlee1025 ! I removed renderedNotes from DataSummaryPanel

**Pull request merged**
