### PR TITLE
Implement @HPI shortcut

### PR DESCRIPTION
**Pull request by danlee1025**
Address JIRA-816

To use shortcut, first type "@condition" and then "@HPI" shortcut should appear in the context panel.  A blob of text should get added to the editor describing the patient and the current condition.  The history of the patient's procedures, medications, lab results, and most recent disease status will also appear in chronological order.

Shortcomings:
- The buildHpiNarrative(along with some other functions to get recent lab results) had to be duplicated in FluxCondition and FluxInjury for the "@hpi" shortcut to work with the Fracture condition and the conditions in /p3.  Ideally, we would only want to have to write these functions once in FluxCondition and have any other condition classes inherit the functions.  We will try to improve on our wrapper classes when we import the new ES6 classes.

- Text printing out the events in chronological is going to feel really repetitive since I am just using a template and including the event name and dates.  Let me know if you have an idea for improving this or if you think the text should say something else.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
-  Cheat sheet is updated
-  Demo script is updated 
-  Documentation on Wiki has been updated 
-  Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
-  Added UI tests for slim mode 
-  Added UI tests for full mode
-  Added backend tests for fluxNotes code
-  Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
[GQ1] One minor thing. FluxCondition, FluxBreastCancer, FluxInjury, and other model classes shouldn't know anything about summary metadata or summary or any other UI usage of the model data. They should only know about model data. Comments mention that methods are for summary and they shouldn't mention that. Hopefully, the methods are generic methods to provide back data in various forms and that's all. Can you just remove the comments about summary. Do you think the methods are specific to our summary functionality right now? I know we discussed this before you implemented and we put the buildHPINarrative method in the model objects which wasn't ideal but can still be about aggregating data about the object and returning it in a narrative form.

**Comment by danlee1025** [comment]
For GQ1, which comments are you specifically talking about?  Line 181 in FluxBreastCancer?

**Comment by gregquinn2001** [comment]
sorry, I meant to put that in. If you search the model classes for summary you should find them

**Comment by gregquinn2001** [comment]
one of them was actually already there on master

**Comment by danlee1025** [comment]
For the comment that states "Starts with initial summary of patient information", I'm just stating that the hpi narrative begins with a summary of the patient, like their name, age, gender, and condition.  Do you think that is ok or should I rephrase without mentioning summary?

I can modify the other comment in getMostRecentLabResults that mentions summary metadata.

**Comment by gregquinn2001** [comment]
no I agree that one is fine. It's any that refer to the targeted data panel/summary ui component that need to go.

**Pull request merged**
