### PR TITLE
Add copy reset buttons

### PR DESCRIPTION
**Pull request by nicoleng12**
Copy and reset buttons added to top of shortcut viewer.

Implemented reset button. Clicking on progression or toxicity shortcuts  then clicking on reset button brings the form back to currentShortcut is null state.

### CODE REVIEW

**Comment by gregquinn2001** [comment]
looks good to me. I vote merge.

**Comment by gregquinn2001** [comment]
can you eliminate the compile warning?

**Comment by nicoleng12** [comment]
Fixed. I had a typo. Thanks

**Comment by gregquinn2001** [comment]
Cool. I vote merge.

**Pull request merged**
