### PR TITLE
Add dates to lab results

### PR DESCRIPTION
**Pull request by nicoleng12**
Added dates to lab results:

- Updated harcodedpatient.json to include more entries for lab results and added clinically relevant time
- Dates for the lab results appear next to the value (this is where we are putting the dates currently since lab results are part of the summary section which uses the name/value pairs data type)
- Added functionality to sort lab results chronologically
- Added a max age for lab results. In SummaryMetaData, changing the maxAgeInYears variable in the getMostRecentLabResults method changes this threshold value. Only lab results that fall within this threshold are displayed

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- N/A Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Very cool! I think putting the date with the value is the best we can do right now due to limitations of name-value pair visualizers. One potential issue
[GQ1] I think only the most recent lab result of a type should be displayed in the most recent lab results. Of course, only lab results associated with the current condition are shown as well.

**Comment by gregquinn2001** [comment]
[GQ2] Some of the methods in SummaryMetadata should be available on FluxBreastCancer class in model/oncology folder. They used to be in PatientRecord but are now being migrated to the correct model object. UI should be able to ask the model of a Breast Cancer condition for its most recent lab test results. If the most recent lab test of a type is older the x months, it may not show up and should be missing potentially instead. For now, we can just return the most recent result of each unique type associated with the breast cancer condition. Not sure if that's what we are doing other than the one per type part which is covered by GQ1 above.

**Comment by nicoleng12** [comment]
Currently working on GQ1 and GQ2. Will let you know when those fixes have been pushed

**Comment by jafeltra** [comment]
This is something that I just thought of that I forgot to do before too, but should we update the HardCodedPatient JSON in the shr-node-server repository as well?

**Comment by gregquinn2001** [comment]
We need to update the one in the server-side repository at some point. I think we should just create a task for next sprint to do that and test things. It would be nice if we could have it in one place and reference it from everywhere it's used!

**Comment by nicoleng12** [comment]
@gregquinn2001 I addressed GQ1 and GQ2. I also rebased the branch.

**Comment by gregquinn2001** [comment]
Oops a back-end test fails too!

**Comment by nicoleng12** [comment]
Fixed the dates and travis tests and back end tests pass now

**Pull request merged**
