### PR TITLE
Mid year demo patient

### PR DESCRIPTION
**Pull request by gregquinn2001**
JIRA 872. Created a mid-year demo patient in SHR JSON format. HardCodedReadOnlyDataSource can load this patient as well as the default hard coded patient. Updated FullApp to accept a patient id for an endpoint and defined a new endpoint at myd18 that loads the mid-year demo patient.

The mid-year demo patient matches the data that Joey defined within the sample note he created for a metastatic breast cancer patient. All structured data that SHR is capable of representing (or most at least) exists in structured form within the mid-year demo patient json. Recent clinical notes representing the most recent encounters matching the history of present illness in the sample note are also provided in the hard code patient SHR json.

To test, go to http://localhost:3000/myd18.

Testing the regular patient endpoint would be good too.

Added support to display genetics info in targeted data panel.

Also made a number of displays (like medications graphical viz) more robust and handle missing data better.

Also created a number of JIRA issues discovered as part of this.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [ ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [ ] Code is commented

**Tests**

- [x] Existing tests passed
- [ ] Added UI tests for slim mode 
- [ ] Added UI tests for full mode
- [ ] Added backend tests for fluxNotes code
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
From demo dry run today.
[GQ1] Add dosages for all chemotherapy drugs including at least one out of typical range
[GQ2] Add additional disease status values from past
[GQ3] Pull lab results from Hernandez into Ortiz
[GQ4] Pull Fracture condition from Hernandez into Ortiz

**Comment by gregquinn2001** [comment]
GQ1-5 all addressed.

JIRA 956 also addressed now. Do @condition choosing carcinoma then do @hpi and notice that procedures also include results now.

**Comment by gregquinn2001** [comment]
Added fix for JIRA 946 as well (disease status graph y axis labelling)

**Comment by danlee1025** [comment]
[DL1] On /patient in pre-encounter mode, the disease status graph y values do not all appear.  I think the yTicks need to be sorted(Seems to be the change from master.).  
[DL2] Not a bug on this branch, but in the codeToValueMap in ProgressionLineChartVisualizer, there is a duplicate mapping.  Can you change mapping of "C0677874" to 3.

**Comment by gregquinn2001** [comment]
DL1 and DL2 should be fixed! Thanks @danlee1025

**Comment by gregquinn2001** [comment]
Renamed some methods for consistency within model per @danlee1025 suggestion

**Comment by gregquinn2001** [comment]
rebased

**Comment by danlee1025** [comment]
Added error handling when no review of systems found on patient.  Added review of system entries to myd patient.

**Comment by jafeltra** [comment]
This looks good! I did find a few bugs.

[JA1] @reason for  previous visit is broken in both /patient and /myd18. Inserting the Reason for Visit from the Targeted Data Panel breaks as well.
[JA2] Inserting stage from the Targeted Data Panel breaks on /myd18.

**Comment by danlee1025** [comment]
JA1 should be fixed.  Just had to add the new function name to shortcuts.json.

**Comment by jafeltra** [comment]
JA2 is due to the fact that I was trying to insert the existing staging value before using a #staging creator. The StageInserter has StagingCreator as it's parent context. I talked to Dan and we think the StageInserter should have a ConditionInserter parent context, and then return the stage for the specific condition, if it has a stage. @gregquinn2001 does that seem like the right way to approach fixing this?

**Comment by jafeltra** [comment]
I realized that doesn't actually solve the problem. When you try to insert the staging value from the Targeted Data Panel, you still would need a condition specified before it can be inserted.

**Comment by gregquinn2001** [comment]
Yes! Good call. I agree!

**Comment by gregquinn2001** [comment]
You should need a condition (a breast cancer one specifically)

**Comment by gregquinn2001** [comment]
but a patient can have multiple staging values as well so hence the staging context requirement. @current staging would make sense with condition context only and it would find the lastest staging and get the stage from that

**Comment by gregquinn2001** [comment]
we don't have an @staging so you can't use @stage when you should be able to right now

**Comment by jafeltra** [comment]
That does make sense to me. I'm not sure what the best way to move forward with this is. Should we implement the @current staging shortcut like you said in order to fix this? One quicker fix we could do is take the shortcut off of the Stage section in summary metadata, but that doesn't seem like the best thing to do since it is an inserter and we would want to capture that as structured data. I was also thinking maybe we could add it as plain text if the parent context was not set, but after talking to Dan, I'm not sure that is easy to do.

**Comment by jafeltra** [comment]
Updated the list that gets created for inserters so null values don't get printed out. This was happening when using @all medications/@active medications since the units on timingOfDoses was null. Everything else looks good to me!

**Pull request merged**
