### PR TITLE
Support dashed lines in ie

### PR DESCRIPTION
**Pull request by nicoleng12**
_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

This PR addresses jira issues 973 and 1011.
- Replaced text-decoration used in css for underlining structured data, showing missing data, and showing unsigned data with border-bottom instead since text-decoration is not supported in IE
- using border-bottom increased the space between the text and the underline. Also increased px size of border line so that the dashes are more spaced apart. This makes the unsigned data easier to notice in narrative and tabular modes

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- N/A Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- N/A Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by mtorchio** [comment]
I think this looks good! I'm going to run the tests before approving.

**Comment by Dtphelan1** [comment]
[DP1] We're using 1.5px values, which aren't real values and just get rounded up to 2px.   
[DP2] The size of underlines is inconsistent across the app. Some visualizers, like the tabular, use 1px for our underlines whereas the narrative visualizers use 1.5 (actually 2)px. 

Personally, I'm partial to the 1px underlines. I imagine we started using the 1.5/2px to make the dashed lines more pronounced, but they look much heavier when they are solid lines as opposed to dashed. I'm curious how people think we could resolve this. Should we use 2px across the board? Is it okay to use 2px for dashed and 1px for solid? Are we okay with the way the 1px dashed looks (ostensibly not, because we have a JIRA to solve for this).

**Comment by Dtphelan1** [comment]
After some research, redacting DP1 as it's not always true for all browsers.

**Comment by nicoleng12** [comment]
Addressed DP2. Made all underlines 1px and the dashed line 1.4px

**Comment by gregquinn2001** [comment]
Let's ask Edwin if there's still questions about the design. Can someone send him screenshots? I'll take a look as well.

**Comment by nicoleng12** [comment]
@gregquinn2001 Yes, I'm in the middle of sending you, Edwin, and Noranda an email with screenshots actually, lol

**Comment by gregquinn2001** [comment]
Way ahead of me as usual! Thanks!

**Comment by nicoleng12** [comment]
Edwin is sending out a document tomorrow (3/8) with values for the lines. Waiting for document to make changes before merging this

**Pull request merged**
