### PR TITLE
Timeline Updates

### PR DESCRIPTION
**Pull request by cjduffett**
I added progression items and events (e.g. surgery, radiation) to the timeline using font-awesome icons. I also moved the data displayed in the timeline up to App.jsx. All items in the timeline are dynamically assigned groups (rows) in the timeline to ensure there are no conflicts between different items.

For "point-in-time" events, I assigned them a length of 1 day. At any timeline zoom level the icons minimally take up 30px of width so they're still visible at low zoom levels.

For the icons used in the timeline I also created a legend describing what those icons represent.

I'm open to feedback on the overall design/use of icons - I feel like there should be some hover text for the icon timeline items describing them in more detail, or perhaps when you click on them it brings you to their location in the data summary... thoughts?

### CODE REVIEW

**Comment by cjduffett** [comment]
Oh, and all tests for the entire app can now be run using `yarn test`

**Comment by Dtphelan1** [comment]
1. I think you're right re: the hover. In order for this to be an effective viz, we need to communicate the important features of the events we're displaying. The good: we now have an icon for progression events, and when it's would be too small we force a min width so that icon still shows; next steps: let's integrate some hover over text to tell the user what the progression event measured (are they progressing, stable, responding, etc...) and maybe the justification for the measurement (if we have the space.) 

2. When they zoom in to that day, the text should probably display in the bar itself. 

3. Small thing: we should choose a more subtle color, to stick with the palette we've established. Maybe something yellow like #FBEEAD could work, or something else  light/almost pastel similar to the current palette. The green sticks out. 

4. The need for yet another tooltip indicates to me that we should look into turning our tooltips into a UI component sometime in the future. Something to keep in mind.

**Comment by Dtphelan1** [comment]
Also, why are there a  separate class of timeline dates? Shouldn't there just be dates in the patient's record (timestamped used moment.js or not) that are used in the timeline. Currently there's a weird redundancy and a lack of consistency. Have we considered updating this?

**Comment by cjduffett** [comment]
@Dtphelan1 what "class of timeline dates" are you referring to?

**Comment by gregquinn2001** [comment]
how do I get to this code? I tried git checkout timeline/progression-items but it doesn't like that as a branch. never seen branches with slashes...

**Comment by cjduffett** [comment]
Just type the forward slash in the branch name, .e.g:

```
git checkout timeline/progression-items
```

**Comment by gregquinn2001** [comment]
obviously I did! Maybe it's a windows thing. I'll look into it. Can we just avoid forward slashes in the future or is there something special we're trying to achieve?

**Comment by gregquinn2001** [comment]
alright got it to work

**Comment by gregquinn2001** [comment]
let's address or record as a bug each of Dylan's items. Is there a way to dynamically change the width of the bar based on the current scale during rendering if the item is a point in time type maybe?

**Comment by Dtphelan1** [comment]
re: "classes of timeline events" 
You have the same events stored in two places. For one, we have an array of events in state.timelineEvents, and (in some cases) identical events in state.keyDates. Why are these uncoupled, should the timeline just present the keyDates?

**Comment by gregquinn2001** [comment]
yes timeline should present key dates

**Comment by gregquinn2001** [comment]
I really like the legend

**Comment by cjduffett** [comment]
I added @Dtphelan1's suggestion of light yellow for progression events. Looks good.

I adjusted the font size of the legend (it was a little large). I rounded the corners of all timeline items (slightly), and for point-in-time items I made them circular.

Finally, I updated the internal data models to consistently record events/progression items in one place. The same data is now displayed in both the timeline and the data summary panel.

I'm currently working on a detailed popup that appears adjacent to timeline items with more detailed information.

**Comment by gregquinn2001** [comment]
The latest mockup has a Relevant Dates tab which we don't have yet (we should create a jira task to add it though). On that tab though, Edwin has Important Dates and History sections. I think we should just replicate those sections on our main tab for now?

Important Dates
Recurrence               Missing recurrence date
Diagnosis                 Missing diagnosis date
...

History
12 JUL 2012 -                        Radiation
08 AUG 2012
20 JUN 2012                          Lymph node biopsy
...
(from shr_fluxnotes_concepts_v06.pdf - 1.3 FLUX NOTES DATA RETRIEVAL)

**Comment by nicoleng12** [comment]
I really like the legend in the timeline. I agree that adding a hover on the icons would be useful. For example the user can hover over the icon in Jan, 2012 and it will read something like "Initial Diagnosis".  This will help users link the timeline with the data in the summary panel.

I agree with Greg that we can add a jira task to add more tabs for Relevant Dates. I'm almost done with my jira task of making a tab for existing notes so it should be straightforward to add another tab.

I like how you reorganized the unit tests. Looks good!

**Comment by cjduffett** [comment]
I added a hovering item detail view over each item in the timeline. I also added more events and progression observations to the timeline, for variety. I think this is much closer to a design we want.

**Comment by nicoleng12** [comment]
The hovering item detail view is very useful and I like the styling of it. I'm wondering if the hover over in the timeline and the hover over in the right panel (staging form) should be the same style for consistency. I don't have a strong preference for one style over the other. Should we make a new jira item for this?

**Comment by gregquinn2001** [comment]
I like the progression pop-ups although it would be good if icon indicated progression as well so user doesn't have to hover??
Also, pop-ups are not coming up next to icon I'm hovering over

**Comment by cjduffett** [comment]
I am still working on getting the positioning right. For whatever reason the popups end up in different positions on different screen sizes... not sure why this is occurring. I had it right on my desktop screen yesterday, but now it's off on my lab screen and different on my laptop too... may have to do with the way the timeline positions its elements.

**Comment by cjduffett** [comment]
As far as icons go, there is only a limited set of font-awesome icons to choose from that represent medical data. I didn't find any other generic icons that seemed to suit progression, but if you find anything that seems suitable let me know. See: http://fontawesome.io/icons/#medical

**Comment by gregquinn2001** [comment]
I think mine are offset vertically due to scrolling for me to get down to timeline if that helps at all

**Comment by cjduffett** [comment]
I made some adjustments (namely changing the `position` styling attribute from `absolute` to `fixed` to ignore scrolling) and things seem to be working as expected on all screen sizes/zoom levels now. Can you confirm?

**Comment by Dtphelan1** [comment]
I cannot confirm. Still looks weird on my machine

**Comment by gregquinn2001** [comment]
it works on mine great now!

**Comment by gregquinn2001** [comment]
Dylan you ok with Carlton resolving conflicts and merging then?

**Comment by Dtphelan1** [comment]
Absolutely!

**Comment by gregquinn2001** [comment]
Did you modify summary panel as part of this pull request? the key dates section of summary panel should not be changed. this jira item was to add progression items to timeline

**Comment by gregquinn2001** [comment]
can you back out changes to summary panel before merging?

**Comment by cjduffett** [comment]
I will resolve conflict before merging. The changes I made to the summary panel were to reflect consolidation of events in the internal data model.

**Comment by cjduffett** [comment]
Rebased and fixed conflicts. Ready to merge.

**Comment by Dtphelan1** [comment]
Testing now.

**Comment by Dtphelan1** [comment]
Other than Greg's concern about the data summary panel, it looks good on my end.

**Comment by gregquinn2001** [comment]
The progression values should not appear in the list of key dates

**Comment by nicoleng12** [comment]
Looks good when I test it. I like fix you made for the hover position.

**Comment by cjduffett** [comment]
Okay, so part of the conflict between the Data Summary and Timeline panels was the mixing between key dates, progression, and procedures. So I separated them out as follows:

1. The Data Summary panel now separately displays Key Dates (diagnosis, recurrence) and Procedures (mammogram, surgery, radiation). Progression events are not displayed in the summary panel for now (perhaps we add a new tab for this?).

2. The timeline combines key dates and progression into a series of "events" that are displayed in yellow with the heartbeat icon.

3. The timeline displays all procedures in reddish with the hospital icon.

4. I updated the Timeline Legend to reflect these slight changes.

Is everyone OK with the way this is laid out now?

**Comment by cjduffett** [comment]
Merged after approval from @gregquinn2001

**Comment by nicoleng12** [comment]
1. I like the separation. Im currently working on a jira task to add in progression
2. and 3. I like the way you organized this
4. Nice

I'm ok with this layout

**Pull request merged**
