### PR TITLE
New shortcuts no components

### PR DESCRIPTION
**Pull request by gregquinn2001**
Introduction of new narrative shortcut mechanism with right panel context

fixes: 219, 358, 442, 436, 209, 445, 426

Should support progression, toxicity, and staging fully in patient mode. progression and toxicity only in slim mode although adding staging to the list of supported shortcuts in SlimApp adds staging and it does work (I tried it).

**All styling for Slim mode and patient mode should be back to what we had in previous version of apps** even though we use Material UI 1.0 beta 5 now. yarn install will ask you to choose version from list. Always choose 1.0 beta 5 which is default right now. Can someone make yarn install just choose it? I didn't look into that...

### CODE REVIEW

**Comment by nicoleng12** [comment]
Jira issues 219, 358, 442, 436, 209, 445, 426 look to be fixed.

When did yarn install, it did not prompt me for a material ui version but looking at package.json and yarn.lock files show that the code is using material ui 1.0. 

Flux lite styling and functionality appears to be broken. 

In terms of functionality:

Progression form:
- Clicking on the status progression buttons causes an error 
image

- After selecting button, no indication that button is selected (in this example clicked on "Complete Response"
image

- Copy button does not update string with selected values
image

- Buttons correctly change background for rationale section which triggers highlight of button in status section, but user cannot select a different status option

Toxicity form:
- Entering an adverse event and selecting (in this case Anemia) does not select item and gives the following error in the console (same error when selecting in progression form):
image

- Due to previous issue, user is required to click twice before the adverse event is displayed in the text field

- Error when selecting a grade:
image

- Copy button does not update string as values are selected

In terms of styling:

- buttons should be white background (including the copy button)
- button labels should not be in all caps
- clicking on a button should toggle the background color from white to blue. Right now buttons are grey and there is no indication that is is selected (except for rationale progression buttons. These seem to be fine)

**Comment by laclark22** [comment]
I also an seeing what Nicole is seeing. I did get prompt for the Material UI version and picked the one that Greg said in his initial request.  But like Nicole, button selecting functionality is all off and the copy bar is not being update once you do get a button selected.

**Comment by jafeltra** [comment]
I also noticed the same things that Laura mentioned. I was able to select the Material UI version correctly. In addition to the broken functionality on Flux lite, it seemed like I could only add in fields from the right panel after two clicks. I didn't see anything happen on my first click.

**Comment by gregquinn2001** [comment]
fixed the slim mode forms. they work again. simple fix. sorry forgot a test case after fixing something for patient mode! please number issues with your initials going forward so we can reference them. Here are remaining outstanding issues that I see:

NN1: buttons should be white background (including the copy button)
NN2: button labels should not be in all caps

all the rest are related to the 1 issue I fixed above. If you see any other issues besides the 2 above, please report them with a reference code!

**Comment by gregquinn2001** [comment]
NN1 and NN2 fixed as well. also simple fixes. sorry I missed those the first time around.

**Comment by gregquinn2001** [comment]
I just noticed that Julia reported an additional problem. I added the content in brackets to clarify. Let me know if I got it wrong.

JA1: I could only add in fields from the right panel after two clicks. I didn't see anything happen on my first click. [Problem is in patient mode when clicking in right panel on shortcut buttons.]

I can't reproduce this. Let me know if you still see this behavior after pulling the latest. Does anyone else see this behavior?

**Comment by laclark22** [comment]
LC: I went through all the comments and everything looks to be fixed to me. I could not reproduce the problem that @jafeltra saw though. In patient mode it only take one click on the left side for the workspace to populate like we want it to.

**Comment by jafeltra** [comment]
For JA1, I can still reproduce this bug after pulling the latest updates and doing a new yarn install. I get this bug when typing #staging into the editor and then using the buttons on the right panel to start adding the first T value. The value is not added on the first click, but it is added after the second click. If I add in #staging by clicking the button on the right panel, I don't get the same bug, and it works as expected. I believe that Laura also saw the same bug.

**Comment by gregquinn2001** [comment]
I still can't reproduce JA1 (thanks for the precise steps you used to cause it). Are you using Chrome or a different browser?

**Comment by jafeltra** [comment]
I'm using Chrome and it says its on the most up to date version.

**Comment by gregquinn2001** [comment]
So issue JA1 takes the following steps:
1. Click on @condition and choose   Invasive Ductal and Invasive Lobular Breast Carcinoma 
2. Type #staging 
3. Try to click on T2 and nothing happens.
4. Click on T2 again and it works

I can't reproduce, but did I get the steps right?

**Comment by nicoleng12** [comment]
I am able to reproduce the JA1 issue using your steps Greg. Since this jira issue is done in terms of fully implementing the narrative approach, should close this, merge it into master and make a separate jira issue for JA1?

**Comment by jafeltra** [comment]
Yes, those are the steps. I'm not sure if this is something we want to hold up merging this into master since it is a minor bug and you can't reproduce it.

**Comment by gregquinn2001** [comment]
definitely should not hold up merging. Please capture it as a jira bug though in the product backlog. Make sure it is at the top. Strange one!

**Comment by Dtphelan1** [comment]
DP1: In SlimApp, picking an Adverse Event (e.g. Anemia), selecting a grade, and deleting your AE disables the grade buttons but doesn't remove the current grade. 
DP2: Padding on the three patient-mode panels look worse due to the switch to Matierual UI v1.0.0-beta.5
DP3: Drop-shadows due to the upper nav-bar look weird on larger screens. 

Don't know if the buttons were disabled in this PR or not, but either way that bug and these other two are small enough that they could be logged in JIRA and not hold us back.

**Comment by gregquinn2001** [comment]
Actually I reproduced JA1. After typing #staging you have to click on the autocomplete and not type a space to insert it. When you said type, I thought you meant completely typed. So here are the steps:

1. Click on @condition and choose   Invasive Ductal and Invasive Lobular Breast Carcinoma
2. Type #staging (no space after) and click on #staging in autocomplete menu
3. Try to click on T2 and nothing happens.
4. Click on T2 again and it works

**Comment by gregquinn2001** [comment]
DP2 and DP3 are very subjective. I don't think it looks worse at all. Let's hold off on those until we get some feedback from involution and users. You can log them, but don't  make them definitive. we need more opinions

**Comment by gregquinn2001** [comment]
DP1 probably was a problem before too but maybe not. let's log it though and still merge. make sure they all appear at the top of product backlog. Thanks for the thorough testing!

**Comment by jafeltra** [comment]
I should have specified selecting the autocomplete. I made a JIRA issue for the JA1 bug and included Greg's latest set of steps to reproduce. I think the rest of this pull request looks good, although I am less familiar with some of the smaller cases of things that may have changed.

**Comment by Dtphelan1** [comment]
DP1 became a problem once the Grades were disabled. They weren't when my PR was merged on Wednesday. This was a topic of conversation then, and will probably come up again (FYI: I added more comments on that earlier today). No worries about it for now though!

DP3 could be worded more precisely; the drop-shadow of the nav-bar doesn't render across the entire menu, even though its supposed to. This produces the "weirdness" I referenced. I'd say this is more of an observation, but it was definitely worded as a subjective assessment. 

DP2 is definitely subjective, agreed. 

I made a side-by-side of the two for comparison -- in my opinion, the newer version has scattered valleys of white space between content made worse by the diminished padding, the tray-menu isn't centered, the avatar's smaller look leaves too much white space, and I personally just like a little more padding on sides of my panels. I'd love to hear other's feedback though! 

side-by-side-comparision-patient-mode

I'm making JIRA's for all of them, but otherwise it looks good to merge!

**Comment by gregquinn2001** [comment]
Thanks for clarification @Dtphelan1.

**Pull request merged**
