### PR TITLE
Note preview styling

### PR DESCRIPTION
**Pull request by nicoleng12**
Updated clinical notes view in NoteAssistant to follow Involution's design mockups. 

To view, click on clinical notes in the right most panel. The context tray toggles to the clinical notes view

- New Note and Resume in-progress note buttons don't currently work. Functionality is addressed in a separate jira issue
- label shows how many previous notes are available (adding or removing notes in the hard coded patient json updates this number)
- Selector to choose how to sort notes doesn't currently work. Sorting is address in a separate jira issue
- Implemented new note and clinical note svgs from Involution so notes match mockup design
- Added button to view additional notes (this button doesn't currently work. This is part of a different jira task). Developers can set the number of notes to view in NoteAssistant via the maxNotesToDisplay state variable. The label of the view additional notes updates to the correct number of notes not currently being shown
- Notes and buttons scale with screen size 

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- N/A Cheat sheet is updated
- N/A Demo script is updated 
- N/A Documentation on Wiki has been updated 
- N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- N/A Added UI tests for slim mode 
- N/A Added UI tests for full mode
- N/A Added backend tests for fluxNotes code
- N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by Dtphelan1** [comment]
DP1: YHovering over the notes produces a grey background in the top-right corner of the paper, where the folded paper would have been before it folded. This looks weeird and it would be great if we could avoid this.

**Comment by Dtphelan1** [comment]
[DP2] I'm not sure that the resizing ever happens on most monitors, in virtue of the fact that the set width, 5vw, is almost never greater than the min-width, 180px. If my math is right, the dynamic sizing will only trigger on screens 3600px wide.

**Comment by gregquinn2001** [comment]
For DP1, I'd be ok with logging a jira bug and merging this pull request.

**Comment by Dtphelan1** [comment]
I'm okay with that @gregquinn2001!

**Comment by Dtphelan1** [comment]
So once we get feedback on DP2 I'm good to merge!

**Comment by nicoleng12** [comment]
Thanks for reviewing! Made a jira for [DP1] https://jira.mitre.org/browse/ASCODCP-769. For DP2, the set width is 8vw and the minimum width is 180px. I'm okay with increasing the set width so that it appears larger on larger monitors. I am currently working off of my laptop which is using the min width due to the smaller screen size. What size should the set width be set to? Can someone who has a large monitor help to test this?

**Comment by nicoleng12** [comment]
I changed the set width from 8vw to 15 vw. How does that look @Dtphelan1? I don't have access to a large monitor since I'm working on my laptop so let me know if it looks okay on a larger screen

**Comment by nicoleng12** [comment]
After working with @danlee1025 and @Dtphelan1 tested that 9vw looks good. Pushed that change and rebased the branch on master

**Pull request merged**
