### PR TITLE
Refactored 'adding new progression to timeline' test

### PR DESCRIPTION
**Pull request by danlee1025**
Changes:
This test was inconsistent for many people.  I tried to add pauses after clicking on the suggestion boxes but the test was still inconsistent.  I changed the test to choose the structured phrases from the context panel instead of typing it into the editor. 

If the 'Hovering over calendar medication items' test is failing, you have to zoom out on the timeline for the test to pass.  There is a separate JIRA logged to fix this test.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Documentation**

- [x] This pull request describes why these changes were made
- [x] N/A Recognizes any potential shortcomings/bugs in the description 
- [x] N/A Cheat sheet is updated
- [x] N/A Demo script is updated 
- [x] N/A Documentation on Wiki has been updated 
- [x] N/A Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [x] N/A Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- [x] N/A Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- [x] N/A Added UI tests for slim mode 
- [x] Added UI tests for full mode
- [x] N/A Added backend tests for fluxNotes code
- [x] N/A Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by gregquinn2001** [comment]
What did you end up doing? It looks like maybe you deleted the test?

**Comment by danlee1025** [comment]
I refactored the test to use the context panel buttons but moved the test to the context panel section. In git it will look like a deletion and an addition of a test.

**Comment by gregquinn2001** [comment]
@daniellee1025 can you send out a meeting invite for the flux dev team (everyone you add to review your pr) for 30 minutes to discuss UI test issues. We need to decide how we want to handle these going forward. I'm thinking we comment out inconsistent tests until testcafe is updated and then we try them again...

**Comment by nicoleng12** [comment]
The timeline test fails for me but all other tests pass. I can get the timeline test to pass, if, during the test, I manually zoom out on the timeline

**Pull request merged**
