### PR TITLE
Closing of notes implemented

### PR DESCRIPTION
**Pull request by mtorchio**
This adds the Close Note button to the editor. When a note is closed, the editor goes away and the note is deselected but not deleted. The editor can be brought back by clicking an existing or in-progress note. One question about functionality: when the editor is not present, should clicking a template open the editor and insert it? 

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [X] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [X] This pull request describes why these changes were made
- [X] Recognizes any potential shortcomings/bugs in the description 
- [X] Cheat sheet is updated
- [X] Demo script is updated 
- [X] Documentation on Wiki has been updated 
- [X] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [X] Note parser has been updated if structured phrases change

**Code Quality**

- [X] 4-space indents - convert any tabs to spaces
- [X] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [X] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added UI tests for slim mode 
- [ ] Added UI tests for full mode
- [ ] Added backend tests for fluxNotes code
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by mtorchio** [comment]
Resolving failing test before I request review

**Comment by gregquinn2001** [comment]
@mtorchio for your question about templates; when there is no note being authored, the @ "tab" (aka shortcut or context tab) should not be selectable. Nicole has it grayed out. When the note is closed, the note assistant should automatically switch to the clinical notes "tab" in the note assistant the toggle button for the shortcuts tab (@) should be disabled. Please discuss with @nicoleng12 if you're not sure how to do that because I think it should be relatively straight forward.

**Comment by mtorchio** [comment]
Pushed code that addressed:
Greg's comments on the @ tab;
Shortening hostpital names;
Evening out spacing - giving less horizontal space to name;
Close Note is now just Close;
Close button is up higher;
Font size smaller;
Better resolution on grid library (it allows decimal points)

**Comment by gregquinn2001** [comment]
[GQ1] Can we make the red X smaller to match how it appears in the mock-ups (I think)? It looks a little big to me compared to everything else in the area so I checked the mock-ups and I think it does look smaller there.

**Comment by gregquinn2001** [comment]
Functionality is great! It's nice to be able to close the note now and then re-open! Behavior of switching away from shortcuts "tab" in note assistant seems to work well too.

**Comment by gregquinn2001** [comment]
[GQ2] Can we make the height of the button and font size of 'Close' match the mock-ups. The button appears bigger in our implementation than Signed label and value but smaller in the mock-up

**Comment by Dtphelan1** [comment]
[DP1] Can we stick to the using Font Awesome for symbols or icons that aren't straight text, as we do elsewhere in our project? I'm pretty sure there is an icon "fa-times" that will provide an :X: that we can color and style as needed. And my guess is it will size much more pleasantly.

**Comment by Dtphelan1** [comment]
[DP2] Each column in the note-description has no width grid-mediated assigned to it. Regarding the column widths, the idea was to look into weather or not higher resolution values were valid for the library, not to come up with those values and use them.

**Comment by Dtphelan1** [comment]
I've addressed DP1 and DP2.

**Comment by Dtphelan1** [comment]
[DP3] The close note could be position aligned to the right for improved styling.

**Comment by gregquinn2001** [comment]
I may have mislead Mike on the X then. I thought that was just a regular character. :)

**Comment by gregquinn2001** [comment]
this looks good. I rebased and am just waiting for travis then I'll merge

**Pull request merged**
