### PR TITLE
Default visualizer

### PR DESCRIPTION
**Pull request by gregquinn2001**
JIRA 848. Default visualizer can be specified in each summary section by visualizer type (e.g., chart or tabular or narrative, etc.). Defaults specific to workflow/clinical event can also be done.

Added documentation of summary format to top of SummaryMetadata.jsx including defaultVisualizer.

Added a backend test that verifies the default visualizer for medications in pre-encounter is chart.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [ ] Manually tested in Chrome
- [ ] Manually tested in IE

**Documentation**

- [ ] This pull request describes why these changes were made
- [ ] Recognizes any potential shortcomings/bugs in the description 
- [ ] Cheat sheet is updated
- [ ] Demo script is updated 
- [ ] Documentation on Wiki has been updated 
- [ ] Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- [ ] Note parser has been updated if structured phrases change

**Code Quality**

- [ ] 4-space indents - convert any tabs to spaces
- [ ] Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [ ] Code is commented

**Tests**

- [ ] Existing tests passed
- [ ] Added UI tests for slim mode 
- [ ] Added UI tests for full mode
- [ ] Added backend tests for fluxNotes code
- [ ] Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by jafeltra** [comment]
This looks really good to me! The documentation in SummaryMetadata was really helpful and the code was clear. I tested out all three formats for setting default visualizers and they all worked, and they give us a lot of flexibility now! I ran all the tests and everything passes.

It looks like Travis failed, although I'm not sure why. It says that one of the test suites failed to build, but I don't see that happening locally. I can just restart the build if we want to see if that fixes it.

**Comment by gregquinn2001** [comment]
Can you restart the travis build or share how to do that so I can?

**Comment by jafeltra** [comment]
Sure! I just restarted it. If you "Details" next to the travis builds below, there should be a "Restart build" button.

**Comment by gregquinn2001** [comment]
thanks!

**Comment by jafeltra** [comment]
It passed this time! Not sure why it didn't build correctly the first time though.

**Comment by mtorchio** [comment]
This looks good! The code changes make sense for the task. I see where the ordering of the list in VisualizerManager changed back and that the order doesn't matter any longer with the new functionality - verified that the default view for Medications is chart. 

It's a good idea to add comments like the one at the top of SummaryMetadata when the data structures get complicated - and this has definitely reached that point.

I'm going to run the UI tests now.

**Pull request merged**
