### PR TITLE
Added Minimap Section Short Names

### PR DESCRIPTION
**Pull request by noranda**
# Added Minimap Section Short Names

Added minimap section short names to `SummaryMetadata.jsx` for use in minimap labels when the names are too large to fit in the parent container. Short names should be 10 characters or less as described in `SummaryMetadata.jsx`. Logic added to `Child.js` component for minimap that manually renders a clone div to calculate the dimensions of the `minimap-title` div and compares it to its parent div. If either width or height exceeds that of the parent, the short name is used instead.

Tested in Chrome and IE. Other minor changes due to code and editor whitespace cleanup. Unable to add UI test, so needs to be tested manually. Best way to test function is to reduce height of browser until short name is used in a section.

Note: Made minimap styling changes to bring in line with design (fixes contrast and padding issues), but was determined to be out-of-scope for this task, so was commented out for now.

_Pull requests into Flux require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable (**N/A**) and :white_check_mark:._

## Submitter:

**Running the Application**

- [x] Manually tested in Chrome
- [x] Manually tested in IE

**Documentation**

- [x] This pull request describes why these changes were made
- [x] Recognizes any potential shortcomings/bugs in the description 
- Cheat sheet is updated
- Demo script is updated 
- Documentation on Wiki has been updated 
- Additional technical components and libraries are documented and added to wiki as needed

**NoteParser**

- Note parser has been updated if structured phrases change

**Code Quality**

- [x] 4-space indents - convert any tabs to spaces
- Use public class field syntax for binding functions - ex. handleChange = () => { ... };
- [x] Code is commented

**Tests**

- [x] Existing tests passed
- Added UI tests for slim mode 
- Added UI tests for full mode
- Added backend tests for fluxNotes code
- Added note parser examples to test new functionality

## Reviewer 1: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

## Reviewer 2: Name

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by nicoleng12** [comment]
I tested this manually and the resizing works nicely both in chrome and in IE. The names switch to using shortnames when the screen size is small. This branch needs to be rebased with master

[NN1] - The UI test for the mini map fails for me. I get the following error for both chrome and IE:
image

**Comment by noranda** [comment]
NN1 - Yeah this is a tricky test that involves resizing the browser. I'll rebase and then take another look at this.

**Comment by noranda** [comment]
NN1 - Unable to get UI test to work using `resizeWindow`, which doesn't appear to work consistently. So, I removed the test. If this breaks, it only causing some styling issues, so this should be ok. Will need to be tested manually by resizing the browser window.

**Comment by nicoleng12** [comment]
I think we tried adding tests in the past that involved resizing windows and it didn't work so I think removing the test is fine and we can just test manually.

The rest of the tests pass in IE and in chrome. Looks good!

**Pull request merged**
